import { describe, expect, test } from "bun:test";
import { Composition, contribution, corePack, definePack, packIdsFor } from "bounded/domain";
import { watchedRulesOf } from "./watched-rules.ts";
import { protectedPathsPack } from "bounded/protected-paths";

const project = definePack({
  id: packIdsFor("test-packs")("project"),
  dependsOn: [protectedPathsPack],
  contributes: [
    contribution(protectedPathsPack.points.protectedPaths, [
      { match: "packages/db/**", except: ["packages/db/src/schema/**"], deny: ["create", "modify", "delete"], redirect: "Change the schema and run the generator", why: "generated by the schema" },
      { match: "secrets", deny: ["read"], redirect: "Ask the owner" },
      { match: "vendor", deny: ["delete"], redirect: "Keep vendored code" },
    ]),
  ],
});

describe("the protected-paths pack watches what it protects from writes", () => {
  test("every rule that denies a write becomes a watched path, and only those: read-only rules do not, and the protected-paths pack adds none", () => {
    const all = [corePack, protectedPathsPack, project];
    const composed = Composition.compose(all, all);
    if (!composed.ok) throw new Error(composed.error);
    const watched = watchedRulesOf(composed.value, protectedPathsPack.points.protectedPaths);
    if (!watched.ok) throw new Error(watched.error);
    expect(watched.value.map(({ rule, fromPackId }) => [rule.match, rule.except, fromPackId.value])).toEqual([
      ["packages/db/**", ["packages/db/src/schema/**"], "bounded/protected-paths"],
      ["vendor", [], "bounded/protected-paths"],
      ["vendor/**", [], "bounded/protected-paths"],
    ]);
    const db = watched.value.find(({ rule }) => rule.match === "packages/db/**")?.rule;
    expect(db?.why).toBe("generated by the schema");
    expect(db?.redirect).toBe("Change the schema and run the generator");
    expect(watched.value.find(({ rule }) => rule.match === "vendor")?.rule.why).toBe("the protected-paths pack protects 'vendor'");
  });

  test("a watched path forbids only the changes its rule denies, for the project's rules alone", () => {
    const all = [corePack, protectedPathsPack, project];
    const composed = Composition.compose(all, all);
    if (!composed.ok) throw new Error(composed.error);
    const watched = watchedRulesOf(composed.value, protectedPathsPack.points.protectedPaths);
    if (!watched.ok) throw new Error(watched.error);
    expect(watched.value.map(({ rule }) => [rule.match, rule.changes])).toEqual([
      ["packages/db/**", ["create", "modify", "delete"]],
      ["vendor", ["delete"]],
      ["vendor/**", ["delete"]],
    ]);
  });

  test("without the protected-paths pack selected, it watches nothing", () => {
    const composed = Composition.compose([corePack, protectedPathsPack], [corePack]);
    if (!composed.ok) throw new Error(composed.error);
    expect(watchedRulesOf(composed.value, protectedPathsPack.points.protectedPaths)).toEqual({ ok: true, value: [] });
  });
});
