// The domain emitter (ADR LEG-2026-059/060, TN-26-012 §7): every domain concept
// contract of every context → its `<Name>Impl` skeleton and its generated laws.
//
//   contexts/<ctx>/src/domain/<area>/<concept>.contract.ts      architect
//     → <concept>.ts            skeleton   (then the builder's)
//     → <concept>.laws.test.ts  generated  (write-denied, drift-checked)
//
// The skeleton is the worked example's implementation file with every member
// body replaced by a NotImplementedError throw. Its tail is the example's two
// exports, byte for byte, because the tail is not the builder's to write:
//
//   export type NoteText = Contract.NoteText;
//   export const NoteText: Contract.NoteTextFactory = NoteTextImpl;
//
// The builder writes only the class body (ADR LEG-2026-059), and the `impl-tail`
// lint rule keeps the tail as generated. The skeleton imports
// NotImplementedError from the context's red-phase errors module,
// `domain/shared/errors.ts` (generated by ts-hexagonal, removed by delivery).
//
// Pure: facts in, files out; never touches the disk.

import type { EmittedFile, Emitter, ProjectFacts, WorkspaceFacts } from "../pack.ts";
import type { DomainConceptModel, FactoryMember, MethodModel } from "./feature-model.ts";
import {
  acceptsExamplesOf,
  DomainConceptError,
  isDomainConceptPath,
  lawsPathOf,
  parseDomainConcept,
} from "./domain-concept.ts";
import { compareSpecifiers, conceptLawsSource, type ConceptSampleSource } from "./value-object-laws.ts";

/** Where a domain skeleton imports NotImplementedError from. */
export const ERRORS_SPECIFIER = "../shared/errors.ts";

/** `domain/shared/errors.ts`, byte for byte as TN-26-012 §5 fixes it. The
 *  generated file is ts-hexagonal's (red phase only; delivery removes it);
 *  the text lives here so the scaffold bridge and that emitter agree. */
export const NOT_IMPLEMENTED_MODULE_SOURCE = `// Generated for the red phase; delivery removes it.
export class NotImplementedError extends Error {
  constructor(member: string) {
    super(\`Not implemented: \${member}\`);
    this.name = "NotImplementedError";
  }
}
`;

/** The two exports every concept implementation ends with (ADR LEG-2026-059). */
export function conceptTail(name: string): string {
  return `export type ${name} = Contract.${name};\nexport const ${name}: Contract.${name}Factory = ${name}Impl;\n`;
}

function signature(method: MethodModel): string {
  const params = method.parameters.map((p) => `${p.name}: ${p.type.text}`).join(", ");
  return `${method.name}(${params}): ${method.returns.text}`;
}

function throwing(head: string, label: string): string[] {
  return [`  ${head} {`, `    throw new NotImplementedError(${JSON.stringify(label)});`, "  }"];
}

/**
 * The implementation skeleton of one concept: the contract's own imports,
 * NotImplementedError and the contract namespace, then `<Name>Impl` with the
 * brand declared, the constructor written out (it is mechanical: a value
 * object's is private over its fields, an entity's is public over the
 * factory's `new` parameters), every factory member as a throwing static and
 * every instance method as a throwing method, then the tail.
 */
export function implementationSkeleton(model: DomainConceptModel): string {
  const name = model.name;
  const importLines = new Map<string, string>();
  for (const imp of model.imports) {
    importLines.set(imp.specifier, `import type { ${[...imp.names].sort().join(", ")} } from "${imp.specifier}";`);
  }
  importLines.set(ERRORS_SPECIFIER, `import { NotImplementedError } from "${ERRORS_SPECIFIER}";`);
  importLines.set(`./${model.stem}.contract.ts`, `import type * as Contract from "./${model.stem}.contract.ts";`);

  const out: string[] = [...[...importLines.keys()].sort(compareSpecifiers).map((s) => importLines.get(s)!), ""];
  out.push(`class ${name}Impl implements Contract.${name} {`);
  out.push(`  declare readonly __brand: ${JSON.stringify(name)};`);
  if (model.kind === "entity") {
    out.push("  constructor(");
    for (const field of model.fields) out.push(`    readonly ${field.name}: ${field.type.text},`);
    out.push("  ) {}");
  } else {
    const params = model.fields.map((f) => `readonly ${f.name}: ${f.type.text}`).join(", ");
    out.push(`  private constructor(${params}) {}`);
  }
  const statics = model.factoryMembers.filter(
    (m): m is Extract<FactoryMember, { kind: "method" }> => m.kind === "method",
  );
  for (const method of statics) {
    out.push("", ...throwing(`static ${signature(method)}`, `${name}.${method.name}`));
  }
  for (const method of model.instanceMethods) {
    out.push("", ...throwing(signature(method), `${name}.${method.name}`));
  }
  out.push("}", "");
  return out.join("\n") + "\n" + conceptTail(name);
}

/** The domain concept contracts of one workspace, parsed, in path order. */
function conceptsOf(workspace: WorkspaceFacts): { model: DomainConceptModel; source: string }[] {
  const domain = `${workspace.sourceRoot}/domain/`;
  return workspace.contracts
    .filter((c) => c.path.startsWith(domain) && isDomainConceptPath(c.path))
    .sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))
    .map((c) => ({ model: parseDomainConcept(c.path, c.source), source: c.source }));
}

/** Every file the domain emits for one workspace. */
export function emitDomain(workspace: WorkspaceFacts): EmittedFile[] {
  const concepts = conceptsOf(workspace);
  const byName = new Map<string, ConceptSampleSource>();
  for (const { model, source } of concepts) {
    if (byName.has(model.name)) {
      const other = byName.get(model.name)!.model.contractPath;
      throw new DomainConceptError(`${model.contractPath}: '${model.name}' is also declared by ${other} — a concept name is unique within its context`);
    }
    byName.set(model.name, { model, examples: acceptsExamplesOf(model.contractPath, source, model.name) });
  }
  const files: EmittedFile[] = [];
  for (const { model } of concepts) {
    files.push({ path: model.implementationPath, content: implementationSkeleton(model), mode: "skeleton" });
    files.push({
      path: lawsPathOf(model.contractPath),
      content: conceptLawsSource(model, byName.get(model.name)!.examples, (n) => byName.get(n)),
      mode: "generated",
    });
  }
  return files;
}

/**
 * The ts pack's domain emitter. The ts pack's own gates call it directly
 * (a pack does not contribute to its own socket; see pack.ts), alongside
 * every contributed `skeletonEmitters` entry.
 */
export const domainEmitter: Emitter = {
  name: "domain-concepts",
  description:
    "Emits each domain concept's <Name>Impl skeleton (<concept>.ts) and its generated laws (<concept>.laws.test.ts) " +
    "from contexts/<context>/src/domain/<area>/<concept>.contract.ts.",
  emit(facts: ProjectFacts): readonly EmittedFile[] {
    return facts.workspaces
      .flatMap((workspace) => emitDomain(workspace))
      .sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  },
};
