// End to end: a project selects the core, the path gate and its own pack of
// rules, and a host adapter dispatches the tool calls it sees.
import { describe, expect, test } from "bun:test";
import { Composition, contribution, corePack, definePack, dispatchEvent, packIdsFor, ToolUse, Verdict } from "bounded/domain";
import { pathGate } from "bounded/path-gate";

const rocketflare = definePack({
  id: packIdsFor("rocketflare")("rules"),
  dependsOn: [pathGate],
  contributes: [
    contribution(pathGate.points.protectedPaths, [
      {
        match: "packages/db/**",
        except: ["packages/db/src/schema/**"],
        deny: ["create", "modify", "delete"],
        redirect: "Edit the schema in packages/db/src/schema, then run `bun db:generate`",
        why: "generated by the schema tool",
      },
      { match: "**/.env*", deny: ["read", "create", "modify", "delete"], redirect: "Ask a maintainer for the value; use .env.example for names" },
      { match: "infra/**", deny: ["delete"], redirect: "Open a change for the platform team" },
    ]),
  ],
});

const selected = [corePack, pathGate, rocketflare];
const composed = Composition.compose(selected, selected);

function judge(tool: string, effects: object[]): Verdict {
  if (!composed.ok) throw new Error(composed.error);
  const call = ToolUse.parse({ role: "builder", tool, effects });
  if (!call.ok) throw new Error(call.error);
  return dispatchEvent(composed.value, call.value);
}

describe("a Rocketflare-like project: core, path gate and the project's rules", () => {
  test("editing generated database code is refused with the project's redirect", () => {
    expect(judge("edit", [{ kind: "write", path: "packages/db/src/client.ts", change: "modify" }])).toEqual(
      Verdict.refuse(
        "bounded/path-gate refused write (modify) packages/db/src/client.ts: the rule 'packages/db/**' from rocketflare/rules denies modify of 'packages/db/src/client.ts' (generated by the schema tool)",
        "Edit the schema in packages/db/src/schema, then run `bun db:generate`",
      ),
    );
  });

  test("editing the schema, the rule's own exception, is allowed", () => {
    expect(judge("edit", [{ kind: "write", path: "packages/db/src/schema/users.ts", change: "modify" }])).toBe(Verdict.allow);
  });

  test("environment files are neither read nor written, anywhere; their names may be listed", () => {
    expect(judge("read", [{ kind: "read", path: "apps/web/.env.local" }])).toMatchObject({ kind: "refuse", redirect: "Ask a maintainer for the value; use .env.example for names" });
    expect(judge("search", [{ kind: "list", root: "apps", filter: null }])).toBe(Verdict.allow);
    expect(judge("write", [{ kind: "write", path: ".env", change: "create" }]).kind).toBe("refuse");
  });

  test("a content search that could read an environment file is refused, even with a filter that cannot rule one out", () => {
    // '.env.tsx' would match both '.env*' and '*.tsx', so the filter proves nothing.
    expect(judge("search", [{ kind: "list", root: "apps", filter: "*.tsx" }, { kind: "read", path: "apps" }]).kind).toBe("refuse");
  });

  test("infrastructure can be changed but not deleted", () => {
    expect(judge("edit", [{ kind: "write", path: "infra/main.tf", change: "modify" }])).toBe(Verdict.allow);
    expect(judge("edit", [{ kind: "write", path: "infra/main.tf", change: "delete" }])).toMatchObject({ kind: "refuse", redirect: "Open a change for the platform team" });
  });

  test("the project's guardrails are protected by the path gate itself", () => {
    expect(judge("edit", [{ kind: "write", path: "bounded.config.ts", change: "modify" }])).toMatchObject({ kind: "refuse", reason: expect.stringContaining("from bounded/path-gate") });
  });

  test("ordinary work goes through", () => {
    expect(
      judge("edit", [
        { kind: "read", path: "apps/web/src/page.tsx" },
        { kind: "list", root: "apps/web/src", filter: "*.tsx" },
        { kind: "write", path: "apps/web/src/page.tsx", change: "modify" },
        { kind: "execute", command: "bun test" },
      ]),
    ).toBe(Verdict.allow);
  });
});
