import { describe, expect, test } from "bun:test";
import { Composition, contribution, corePack, definePack, packIdsFor, watchedPathsOf } from "bounded/domain";
import { pathGate } from "bounded/path-gate";

const project = definePack({
  id: packIdsFor("test-packs")("project"),
  dependsOn: [pathGate],
  contributes: [
    contribution(pathGate.points.protectedPaths, [
      { match: "packages/db/**", except: ["packages/db/src/schema/**"], deny: ["create", "modify", "delete"], redirect: "Change the schema and run the generator", why: "generated by the schema" },
      { match: "secrets", deny: ["read"], redirect: "Ask the owner" },
      { match: "vendor", deny: ["delete"], redirect: "Keep vendored code" },
    ]),
  ],
});

describe("the path gate watches what it protects from writes", () => {
  test("every rule that denies a write becomes a watched path; read-only rules and .bounded/ do not", () => {
    const all = [corePack, pathGate, project];
    const composed = Composition.compose(all, all);
    if (!composed.ok) throw new Error(composed.error);
    const watched = watchedPathsOf(composed.value);
    if (!watched.ok) throw new Error(watched.error);
    expect(watched.value.map(({ rule, fromPackId }) => [rule.match, rule.except, fromPackId.value])).toEqual([
      ["**/bounded.config.*", [], "bounded/path-gate"],
      ["packages/db/**", ["packages/db/src/schema/**"], "bounded/path-gate"],
      ["vendor", [], "bounded/path-gate"],
      ["vendor/**", [], "bounded/path-gate"],
    ]);
    const db = watched.value.find(({ rule }) => rule.match === "packages/db/**")?.rule;
    expect(db?.why).toBe("generated by the schema");
    expect(db?.redirect).toBe("Change the schema and run the generator");
    expect(watched.value.find(({ rule }) => rule.match === "vendor")?.rule.why).toBe("the path gate protects 'vendor'");
  });

  test("a watched path forbids only the changes its rule denies", () => {
    const all = [corePack, pathGate, project];
    const composed = Composition.compose(all, all);
    if (!composed.ok) throw new Error(composed.error);
    const watched = watchedPathsOf(composed.value);
    if (!watched.ok) throw new Error(watched.error);
    expect(watched.value.map(({ rule }) => [rule.match, rule.changes])).toEqual([
      ["**/bounded.config.*", ["create", "modify", "delete"]],
      ["packages/db/**", ["create", "modify", "delete"]],
      ["vendor", ["delete"]],
      ["vendor/**", ["delete"]],
    ]);
  });

  test("without the path gate selected, it watches nothing", () => {
    const composed = Composition.compose([corePack, pathGate], [corePack]);
    if (!composed.ok) throw new Error(composed.error);
    expect(watchedPathsOf(composed.value)).toEqual({ ok: true, value: [] });
  });
});
