// The file a project needs for pi to load bounded: pi discovers project
// extensions under .pi/extensions/, and runs each one's default export.

/** A file to write into a project: its project-relative path and content. */
export interface ProjectFile {
  readonly path: string;
  readonly content: string;
}

const PATH = ".pi/extensions/bounded/index.ts";

/**
 * The loader: it finds the project root from its own location, so the file
 * is the same in every checkout, and hands it to the pi extension bounded
 * carries (bounded/hosts/pi, bundled at pack time; ADR 2026-016), which the
 * project installs as a dependency. If it cannot be loaded or the
 * extension throws, pi would run the session unguarded, so the loader then
 * blocks every tool call instead. Pure: the caller writes the file.
 */
export function piLoader(): ProjectFile {
  const climb = PATH.split("/").slice(1).map(() => "..").join("/");
  const content = `// Generated by bounded. pi loads this file as the project's bounded extension.
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), ${JSON.stringify(climb)});

export default async function (pi: { on(event: string, handler: (...args: unknown[]) => unknown): unknown }): Promise<void> {
  try {
    const { bounded } = await import("bounded/hosts/pi");
    await bounded(root)(pi);
  } catch (error) {
    const cause = (error instanceof Error ? error.message : String(error)).split("\\n")[0];
    const reason = \`bounded could not load, so every tool call is blocked: \${cause}\`;
    pi.on("tool_call", () => ({ block: true, reason: \`\${reason}\\nInstall bounded in this project (\${root}) with npx bounded init, then start a new pi session\` }));
  }
}
`;
  return { path: PATH, content };
}
