// The file a project needs for pi to load bounded: pi discovers project
// extensions under .pi/extensions/, and runs each one's default export.

/** A file to write into a project: its project-relative path and content. */
export interface ProjectFile {
  readonly path: string;
  readonly content: string;
}

const PATH = ".pi/extensions/bounded/index.ts";

/**
 * The loader: it finds the project root from its own location, so the file
 * is the same in every checkout, and hands it to bounded-pi, which the
 * project installs as a dependency. Pure: the caller writes the file.
 */
export function piLoader(): ProjectFile {
  const climb = PATH.split("/").slice(1).map(() => "..").join("/");
  const content = [
    "// Generated by bounded. pi loads this file as the project's bounded extension.",
    'import { dirname, resolve } from "node:path";',
    'import { fileURLToPath } from "node:url";',
    'import { bounded } from "bounded-pi";',
    "",
    `export default bounded(resolve(dirname(fileURLToPath(import.meta.url)), ${JSON.stringify(climb)}));`,
    "",
  ].join("\n");
  return { path: PATH, content };
}
