// Test support for the ts pack's gate tests: the notebook pipeline fixture
// (packs/ts/scripts/testdata/pipeline/) laid into a throwaway monorepo.
//
//   design   the TN and five contracts: NoteId, NoteText, Note; create-note
//            (a command) and list-notes (a query), both exposed via tRPC; a
//            web app declared in the TN
//   tests    the test-writer's files at every level, the app smoke test included
//   build    the builder's implementations (the web app's composition root is generated)
//   half     a half-written create-note handler (for the isolation proof)
//   tests-drizzle, build-drizzle   the Drizzle store tests, schema, stores and
//            mapper, for a composition with ts-drizzle-postgres
//
// Fixture files end in `.txt` so neither the harness's compiler nor its test
// runner collects them; `{{scope}}` becomes the project's package scope.

import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative } from "node:path";
import { writeProjectPacks } from "../../../src/project-composition.ts";
import { harnessRootOf } from "./project-config.ts";
import { generatedManifests, manifestPath, serializeManifest } from "./project-package.ts";

export const PIPELINE = join(import.meta.dirname, "testdata", "pipeline");
export type PipelineStage = "design" | "tests" | "build" | "half" | "tests-drizzle" | "build-drizzle";
export const PIPELINE_PACKS = ["ts", "ts-hexagonal", "ts-trpc", "ts-web"] as const;
export const CONTEXT_SRC = "contexts/notebook/src";

function walk(dir: string): string[] {
  return readdirSync(dir).sort().flatMap((name) => (statSync(join(dir, name)).isDirectory() ? walk(join(dir, name)) : [join(dir, name)]));
}

/** The project-relative files of one stage, with their text for `scope`. */
export function stageFiles(stage: PipelineStage, scope: string): Map<string, string> {
  const out = new Map<string, string>();
  if (stage === "half") {
    out.set(`${CONTEXT_SRC}/application/notes/create-note/create-note.handler.ts`,
      readFileSync(join(PIPELINE, "half", "create-note.handler.ts.txt"), "utf8").replaceAll("{{scope}}", scope));
    return out;
  }
  const root = join(PIPELINE, stage);
  for (const file of walk(root)) {
    out.set(relative(root, file).replace(/\.txt$/, ""), readFileSync(file, "utf8").replaceAll("{{scope}}", scope));
  }
  return out;
}

/** Write one stage's files into a project. */
export function placeStage(project: string, stage: PipelineStage, scope: string): void {
  for (const [path, text] of stageFiles(stage, scope)) {
    mkdirSync(dirname(join(project, path)), { recursive: true });
    writeFileSync(join(project, path), text);
  }
}

export interface Fixture {
  readonly dir: string;
  readonly scope: string;
  readonly cleanup: () => void;
}

/**
 * A throwaway project composing the pipeline's packs, named `demo` (scope
 * `@demo`), with the given stages laid in. Its config was not generated by
 * `bounded init`, so the config-drift check does not apply to it.
 */
export function pipelineProject(stages: readonly PipelineStage[] = ["design"], packs: readonly string[] = PIPELINE_PACKS): Fixture {
  const dir = mkdtempSync(join(tmpdir(), "bounded-pipeline-"));
  writeProjectPacks(dir, packs);
  writeFileSync(join(dir, "package.json"), `${JSON.stringify({ name: "demo", private: true, type: "module", workspaces: ["contexts/*", "apps/*"] }, null, 2)}\n`);
  for (const stage of stages) placeStage(dir, stage, "@demo");
  if (stages.includes("design")) writeWorkspaceManifests(dir, packs);
  return { dir, scope: "@demo", cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}

/** The workspace manifests the design derives (ADR 2026-061), as the design
 *  gate's config sync would write them: the layout lint rules read each
 *  workspace's package name from them. The root manifest is left as is. */
export function writeWorkspaceManifests(dir: string, packs: readonly string[] = PIPELINE_PACKS): void {
  const generated = generatedManifests(dir, packs, join(harnessRootOf(), "packs"), "demo");
  for (const [workspace, manifest] of generated.manifests) {
    if (workspace === "") continue;
    mkdirSync(join(dir, workspace), { recursive: true });
    writeFileSync(join(dir, manifestPath(workspace)), serializeManifest(manifest));
  }
}
