import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, describe, expect, test } from "vitest";
import { readGuardLog } from "../../../src/guard-log.ts";
import { writeProjectPacks } from "../../../src/project-composition.ts";
import { runDeliver, SURFACE_SCRIPT } from "./deliver.ts";
import { runDesignGate } from "./design-gate.ts";
import { runGreenGate } from "./green-gate.ts";
import { runMutationScore } from "./mutation-score.ts";
import {
  configDrift,
  configDriftBlock,
  configDriftReason,
  generatedConfig,
  syncConfigCommand,
  syncProjectConfig,
} from "./project-config.ts";
import { runRedGate } from "./red-gate.ts";
import { runTests, runTestsGate } from "./run-tests.ts";
import { typecheck } from "./typecheck.ts";
import { typecheckGate } from "./typecheck-gate.ts";
import { exampleProject, fakeLockfileMaker, type Fixture, fixtureHarness } from "./testdata/workspace-fixture.ts";

const agentRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const cleanups: (() => void)[] = [];
afterAll(() => { for (const cleanup of cleanups.splice(0)) cleanup(); });
const fake = { makeLockfile: fakeLockfileMaker };

function fixture(options: Parameters<typeof fixtureHarness>[0] = {}): Fixture {
  const f = fixtureHarness(options);
  cleanups.push(f.cleanup);
  return f;
}

/** The example's tree, its config generated by a sync (with a lockfile that
 *  resolves every pin, made without the registry). */
function synced(f: Fixture): string {
  const p = exampleProject(f);
  cleanups.push(p.cleanup);
  writeFileSync(join(p.project, "package.json"), '{"name":"example"}\n');
  const sync = syncProjectConfig(p.project, f.harness, fake);
  expect(sync.lines.join("\n")).toMatch(/OK/);
  return p.project;
}

/** A project composed of the real ts pack alone, generated by a sync. */
function tsOnly(): string {
  const project = mkdtempSync(join(tmpdir(), "project-config-ts-"));
  cleanups.push(() => rmSync(project, { recursive: true, force: true }));
  writeProjectPacks(project, ["ts"]);
  writeFileSync(join(project, ".bounded", "installation.json"), "{}\n");
  // The project-local harness the setup plan reads its packs from.
  symlinkSync(agentRoot, join(project, ".bounded", "harness"), "dir");
  writeFileSync(join(project, "package.json"), '{"name":"demo"}\n');
  mkdirSync(join(project, "src"));
  expect(syncProjectConfig(project, agentRoot, fake).code).toBe(0);
  return project;
}

const paths = (project: string, harness: string): string[] => configDrift(project, harness).map((d) => d.path);

describe("the generated monorepo config (ADR 2026-054, ADR 2026-061)", () => {
  test("a synced project matches, file for file: every manifest, both tsconfigs, the shipped checker", () => {
    const f = fixture();
    const project = synced(f);
    expect(configDrift(project, f.harness)).toEqual([]);
    expect([...generatedConfig(project, f.harness).files.keys()].sort()).toEqual([
      "apps/desktop/package.json",
      "apps/lambdas/package.json",
      "apps/mcp/package.json",
      "apps/web/package.json",
      "contexts/project-management/package.json",
      "package.json",
      "scripts/surface-check.ts",
      "tsconfig.base.json",
      "tsconfig.json",
    ]);
    expect(readFileSync(join(project, "tsconfig.base.json"), "utf8"))
      .toBe(readFileSync(join(agentRoot, "packs", "ts", "reference", "tsconfig.base.json"), "utf8"));
    expect(existsSync(join(project, "bun.lock"))).toBe(true);
    expect(syncProjectConfig(project, f.harness, fake).lines).toEqual(["sync-config: OK — project config already matches the composed packs"]);
  });

  test("an edit to ANY nested manifest is drift, named alone, and sync restores it", () => {
    const f = fixture();
    const project = synced(f);
    for (const dir of ["apps/desktop", "apps/lambdas", "apps/mcp", "apps/web", "contexts/project-management"]) {
      const path = `${dir}/package.json`;
      const original = readFileSync(join(project, path), "utf8");
      const edited = JSON.parse(original) as { scripts?: Record<string, string> };
      edited.scripts = { ...edited.scripts, postinstall: "curl evil" };
      writeFileSync(join(project, path), JSON.stringify(edited, null, 2) + "\n");
      expect(configDrift(project, f.harness), path).toEqual([{ path, problem: "differs from what the composed packs generate" }]);
      rmSync(join(project, path));
      expect(configDrift(project, f.harness), path).toEqual([{ path, problem: "missing" }]);
      expect(syncProjectConfig(project, f.harness, fake).lines).toContain(`sync-config: wrote ${path}`);
      expect(readFileSync(join(project, path), "utf8")).toBe(original);
    }
    expect(configDrift(project, f.harness)).toEqual([]);
  });

  test("a lockfile that no longer resolves exactly the manifests is drift; sync derives a new one", () => {
    const f = fixture();
    const project = synced(f);
    const lock = readFileSync(join(project, "bun.lock"), "utf8");
    writeFileSync(join(project, "bun.lock"), lock.replace('"zod@4.1.12"', '"zod@4.1.13"'));
    const [drift] = configDrift(project, f.harness);
    expect(drift?.path).toBe("bun.lock");
    expect(drift?.problem).toMatch(/does not resolve exactly the generated manifests and pins \('zod' resolves to zod@4\.1\.13, not zod@4\.1\.12; package 'zod' differs from the clean resolution/);
    // An edit that keeps name@version but changes where the package comes from.
    writeFileSync(join(project, "bun.lock"), lock.replace(/"zod@4\.1\.12",\s*""/, '"zod@4.1.12", "https://evil.example/zod.tgz"'));
    expect(configDrift(project, f.harness)[0]?.problem).toMatch(/not the default registry/);
    // The fingerprint is the clean resolution's record: without it nothing verifies.
    writeFileSync(join(project, "bun.lock"), lock);
    rmSync(join(project, ".bounded", "lockfile-fingerprint.json"));
    expect(configDrift(project, f.harness)).toEqual([
      { path: ".bounded/lockfile-fingerprint.json", problem: "missing or malformed: nothing records the clean resolution bun.lock must match" },
    ]);
    expect(syncProjectConfig(project, f.harness, fake).lines).toContain("sync-config: wrote .bounded/lockfile-fingerprint.json");
    expect(configDrift(project, f.harness)).toEqual([]);
    rmSync(join(project, "bun.lock"));
    expect(configDrift(project, f.harness)).toEqual([{ path: "bun.lock", problem: "missing" }]);
    expect(syncProjectConfig(project, f.harness, fake).lines).toContain("sync-config: wrote bun.lock");
    expect(configDrift(project, f.harness)).toEqual([]);
  });

  test("a new context in the design is drift until synced: its manifest, and the lockfile that lacks it", () => {
    const f = fixture();
    const project = synced(f);
    mkdirSync(join(project, "contexts", "billing", "src", "domain"), { recursive: true });
    writeFileSync(join(project, "contexts", "billing", "src", "domain", "invoice.contract.ts"), "export interface Invoice {}\n");
    // Every app depends on every context, so each app's manifest moves too.
    expect(paths(project, f.harness)).toEqual([
      "apps/desktop/package.json", "apps/lambdas/package.json", "apps/mcp/package.json", "apps/web/package.json",
      "bun.lock", "contexts/billing/package.json",
    ]);
    const sync = syncProjectConfig(project, f.harness, fake);
    expect(sync.lines).toEqual(expect.arrayContaining(["sync-config: wrote contexts/billing/package.json", "sync-config: wrote bun.lock"]));
    expect(JSON.parse(readFileSync(join(project, "apps/web/package.json"), "utf8")).dependencies["@example/billing"]).toBe("workspace:*");
    expect(configDrift(project, f.harness)).toEqual([]);
  });

  test("a sync that cannot produce the lockfile writes nothing", () => {
    const f = fixture();
    const project = synced(f);
    writeFileSync(join(project, "apps/web/package.json"), "{}\n");
    rmSync(join(project, "bun.lock"));
    const refused = syncProjectConfig(project, f.harness, { makeLockfile: () => { throw new Error("registry unreachable"); } });
    expect(refused.code).toBe(1);
    expect(refused.lines[0]).toMatch(/BLOCK — bun\.lock cannot be produced: .*registry unreachable/);
    expect(refused.lines).toContain("  Nothing was written.");
    expect(readFileSync(join(project, "apps/web/package.json"), "utf8")).toBe("{}\n");
  });

  test("the root manifest records the project's name: a deleted one is restored under the directory's name; a nameless one blocks", () => {
    const f = fixture();
    const project = synced(f);
    const root = readFileSync(join(project, "package.json"), "utf8");
    rmSync(join(project, "package.json"));
    expect(configDrift(project, f.harness)).toEqual([{ path: "package.json", problem: "missing" }]);
    expect(syncProjectConfig(project, f.harness, fake).lines).toContain("sync-config: wrote package.json");
    expect(readFileSync(join(project, "package.json"), "utf8")).toBe(root);
    writeFileSync(join(project, "package.json"), "{}\n");
    expect(() => configDrift(project, f.harness)).toThrow(/has no name, and it records the project's name/);
    expect(configDriftBlock("red-gate", project, f.harness)?.lines.join("\n")).toMatch(/cannot be computed/);
    const refused = syncProjectConfig(project, f.harness, fake);
    expect(refused.code).toBe(1);
    expect(readFileSync(join(project, "package.json"), "utf8")).toBe("{}\n");
  });
});

describe("what is extra: nested config and misplaced dependency directories", () => {
  test("a nested manifest, tsconfig, bunfig or .npmrc that is not generated is drift; one a generator owns is not", () => {
    const f = fixture();
    const project = synced(f);
    const extra = [
      "contexts/project-management/src/package.json",
      "contexts/project-management/src/domain/tsconfig.json",
      "apps/web/bunfig.toml",
      "apps/web/src/.npmrc",
      "docs/package.json",
    ];
    for (const path of extra) {
      mkdirSync(dirname(join(project, path)), { recursive: true });
      writeFileSync(join(project, path), "{}\n");
    }
    // Owned by a composed generator (hex's generatedFileGlobs): its own drift check judges it.
    mkdirSync(join(project, "contexts/project-management/src/adapters/in/trpc"), { recursive: true });
    writeFileSync(join(project, "contexts/project-management/src/adapters/in/trpc/package.json"), "{}\n");
    expect(paths(project, f.harness)).toEqual([...extra].sort());
    const sync = syncProjectConfig(project, f.harness, fake);
    for (const path of extra) expect(sync.lines).toContain(`sync-config: removed ${path} (no composed pack generates it)`);
    expect(configDrift(project, f.harness)).toEqual([]);
  });

  test("node_modules belongs at the root and directly under a generated workspace, nowhere else", () => {
    const f = fixture();
    const project = synced(f);
    const expected = ["node_modules/x", "apps/web/node_modules/@example", "contexts/project-management/node_modules/zod", "apps/mcp/Node_Modules"];
    for (const dir of expected) mkdirSync(join(project, dir), { recursive: true });
    expect(configDrift(project, f.harness)).toEqual([]);
    const misplaced = [
      "apps/node_modules",
      "apps/unknown/node_modules",
      "contexts/project-management/src/node_modules",
      "apps/web/src/client/node_modules",
      "docs/node_modules",
    ];
    for (const dir of misplaced) mkdirSync(join(project, dir, "zod"), { recursive: true });
    expect(paths(project, f.harness)).toEqual([...misplaced].sort());
    expect(configDrift(project, f.harness).find((d) => d.path === "apps/node_modules")?.problem).toMatch(/where none belongs/);
    const sync = syncProjectConfig(project, f.harness, fake);
    for (const dir of misplaced) expect(sync.lines).toContain(`sync-config: removed ${dir} (no composed pack generates it)`);
    for (const dir of expected) expect(existsSync(join(project, dir)), dir).toBe(true);
    expect(configDrift(project, f.harness)).toEqual([]);
  });

  test("a context's drizzle.config.ts is its generator's, not config drift; one anywhere else is", () => {
    const f = fixture();
    const project = synced(f);
    writeFileSync(join(project, "contexts/project-management/drizzle.config.ts"), "export default {};\n");
    expect(configDrift(project, f.harness)).toEqual([]);
    writeFileSync(join(project, "apps/web/drizzle.config.ts"), "export default {};\n");
    writeFileSync(join(project, "drizzle.config.ts"), "export default {};\n");
    expect(paths(project, f.harness)).toEqual(["apps/web/drizzle.config.ts", "drizzle.config.ts"]);
  });

  test(".git or .bounded below the root is drift, whatever it holds", () => {
    const f = fixture();
    const project = synced(f);
    for (const dir of ["apps/web/.git", "contexts/project-management/src/.bounded", "docs/.GIT"]) mkdirSync(join(project, dir), { recursive: true });
    expect(paths(project, f.harness)).toEqual(["apps/web/.git", "contexts/project-management/src/.bounded", "docs/.GIT"]);
  });

  test("root config names no pack generates are drift: other package managers' lockfiles, bunfig, stray tsconfigs", () => {
    const f = fixture();
    const project = synced(f);
    for (const name of ["package-lock.json", "yarn.lock", "bunfig.toml", "tsconfig.build.json", ".npmrc", "docker-compose.yml"]) {
      writeFileSync(join(project, name), "\n");
    }
    expect(paths(project, f.harness)).toEqual([".npmrc", "bunfig.toml", "docker-compose.yml", "package-lock.json", "tsconfig.build.json", "yarn.lock"]);
  });

  test("pi's own package installs are the host's, not drift; the rest of .pi is still walked", () => {
    const f = fixture();
    const project = synced(f);
    for (const dir of [".pi/npm/node_modules/pi-subagents", ".pi/git/example/node_modules", ".pi/extensions/node_modules"]) {
      mkdirSync(join(project, dir), { recursive: true });
    }
    writeFileSync(join(project, ".pi", "npm", "package.json"), "{}\n");
    expect(paths(project, f.harness)).toEqual([".pi/extensions/node_modules"]);
  });
});

describe("root config files with {{project}} (TN-26-012 §10)", () => {
  test("the Postgres pack's docker-compose.yml and .env.example are generated with the project's name", () => {
    const project = mkdtempSync(join(tmpdir(), "project-config-pg-"));
    cleanups.push(() => rmSync(project, { recursive: true, force: true }));
    writeProjectPacks(project, ["ts", "ts-hexagonal", "ts-drizzle-postgres"]);
    writeFileSync(join(project, ".bounded", "installation.json"), "{}\n");
    writeFileSync(join(project, "package.json"), '{"name":"shop"}\n');
    // What the core's init copy leaves: the pack's file, placeholder and all.
    const raw = readFileSync(join(agentRoot, "packs", "ts-drizzle-postgres", "reference", "docker-compose.yml"), "utf8");
    writeFileSync(join(project, "docker-compose.yml"), raw);
    expect(syncProjectConfig(project, agentRoot, fake).lines).toEqual(expect.arrayContaining([
      "sync-config: wrote docker-compose.yml", "sync-config: wrote .env.example",
    ]));
    expect(readFileSync(join(project, "docker-compose.yml"), "utf8")).toBe(raw.replace("{{project}}", "shop"));
    expect(readFileSync(join(project, ".env.example"), "utf8")).toBe("DATABASE_URL=postgres://postgres:postgres@localhost:5432/shop\n");
    expect(configDrift(project, agentRoot)).toEqual([]);
    writeFileSync(join(project, "docker-compose.yml"), raw);
    expect(configDrift(project, agentRoot)).toEqual([{ path: "docker-compose.yml", problem: "differs from what the composed packs generate" }]);
  });
});

describe("bounded sync-config reinstalls through the composed setup commands", () => {
  test("a sync that changed config runs `bun install --frozen-lockfile --ignore-scripts`; an unchanged, installed one runs nothing", () => {
    const project = tsOnly();
    const ran: string[] = [];
    const run = (command: string, args: readonly string[], cwd: string): void => {
      ran.push([command, ...args].join(" "));
      mkdirSync(join(cwd, "node_modules", ".bun"), { recursive: true });
    };
    writeFileSync(join(project, "tsconfig.json"), "{}\n");
    const first = syncConfigCommand(project, agentRoot, run, fake);
    expect(first.code, first.lines.join("\n")).toBe(0);
    expect(ran).toEqual(["bun install --frozen-lockfile --ignore-scripts --linker isolated"]);
    expect(first.lines).toContain("sync-config: ran bun install --frozen-lockfile --ignore-scripts --linker isolated");
    expect(syncConfigCommand(project, agentRoot, run, fake).code).toBe(0);
    expect(ran).toHaveLength(1);
    rmSync(join(project, "node_modules"), { recursive: true, force: true });
    const broken = syncConfigCommand(project, agentRoot, () => { throw new Error("offline"); }, fake);
    expect(broken.code).toBe(1);
    expect(broken.lines.at(-1)).toMatch(/reinstall failed: bun install --frozen-lockfile --ignore-scripts/);
    const silent = syncConfigCommand(project, agentRoot, () => {}, fake);
    expect(silent.lines.at(-1)).toBe("sync-config: BLOCK — reinstall returned without node_modules/.bun");
  });
});

describe("every tool that spawns the test runner or type-checker refuses drifted config first", () => {
  const noSpawn = (): never => { throw new Error("spawned over drifted config"); };
  const project = tsOnly();
  writeFileSync(join(project, "bunfig.toml"), "[test]\npreload = ['./evil.ts']\n");

  test("run-tests: the primitive and the gate", async () => {
    const raw = await runTests(project, { run: noSpawn });
    expect(raw.blocked).toMatch(/config-drift: .*bunfig\.toml/);
    const gate = await runTestsGate(project, { run: noSpawn });
    expect(gate.lines).toContain("run_tests: route → orchestrator");
  });

  test("typecheck: the primitive and the gate", async () => {
    expect((await typecheck(project, { run: noSpawn })).diagnostics.join("\n")).toMatch(/config-drift: .*bunfig\.toml/);
    expect((await typecheckGate(project, "builder", { run: noSpawn })).lines).toContain("typecheck: route → orchestrator");
  });

  test("mutation-score and the phase gates refuse before running anything", async () => {
    const mutation = await runMutationScore(project, { runSuite: noSpawn });
    expect(mutation.lines, mutation.lines.join("\n")).toContain("mutation-score: route → orchestrator");
    for (const [gate, result] of [
      ["design-gate", await runDesignGate(project)],
      ["red-gate", await runRedGate(project)],
      ["green-gate", await runGreenGate(project)],
    ] as const) {
      expect(result.code, gate).toBe(1);
      expect(result.lines, gate).toContain(`${gate}: route → orchestrator`);
      expect(result.detail["step"], gate).toBe("config-drift");
    }
    expect(readGuardLog(project).filter((e) => (e.detail as { step?: unknown } | undefined)?.step === "config-drift").length).toBeGreaterThanOrEqual(5);
  });

  test("sync removes it, and the project is clean again", () => {
    expect(syncProjectConfig(project, agentRoot, fake).lines).toContain("sync-config: removed bunfig.toml (no composed pack generates it)");
    expect(configDriftReason(project, agentRoot)).toBeUndefined();
  });
});

describe("deliver on a generated project (ADR 2026-054, ADR 2026-062)", () => {
  test("finds the Bun wiring already generated, rewrites no config, and runs the check with bun", () => {
    const project = tsOnly();
    mkdirSync(join(project, "node_modules", "ts-morph"), { recursive: true });
    writeFileSync(join(project, "node_modules", "ts-morph", "package.json"), '{"name":"ts-morph"}\n');
    const before = readFileSync(join(project, "package.json"), "utf8");
    const calls: string[] = [];
    const result = runDeliver(project, {
      run: (command, args) => {
        calls.push([command, ...args].join(" "));
        return { code: 0, stdout: "", stderr: "" };
      },
    });
    expect(result.lines.join("\n")).not.toMatch(/\bnpm\b|experimental-strip-types/);
    expect(calls.every((c) => c.startsWith("bun "))).toBe(true);
    expect(calls.some((c) => c.startsWith("bun add"))).toBe(false);
    expect(readFileSync(join(project, "package.json"), "utf8")).toBe(before);
    expect(JSON.parse(before).scripts["check:surface"]).toBe(SURFACE_SCRIPT);
    expect(configDrift(project, agentRoot)).toEqual([]);
  });
});

describe("where the drift check does not apply, or cannot be computed", () => {
  test("a project not initialized by bounded init has no generated config to compare", () => {
    const project = mkdtempSync(join(tmpdir(), "project-config-legacy-"));
    cleanups.push(() => rmSync(project, { recursive: true, force: true }));
    writeProjectPacks(project, ["ts"]);
    writeFileSync(join(project, "package.json"), "{}\n");
    expect(configDriftBlock("green-gate", project)).toBeUndefined();
    expect(syncProjectConfig(project).code).toBe(1);
    expect(readFileSync(join(project, "package.json"), "utf8")).toBe("{}\n");
  });

  test("an unreadable composition in a generated project is a block, not a pass", () => {
    const project = mkdtempSync(join(tmpdir(), "project-config-broken-"));
    cleanups.push(() => rmSync(project, { recursive: true, force: true }));
    mkdirSync(join(project, ".bounded"));
    writeFileSync(join(project, ".bounded", "installation.json"), "{}\n");
    const block = configDriftBlock("red-gate", project);
    expect(block?.code).toBe(1);
    expect(block?.lines.join("\n")).toMatch(/cannot be computed/);
  });
});

// --- real bun (skipped, with the reason logged, where bun is absent) ----------

const HAS_BUN = spawnSync("bun", ["--version"]).status === 0;
if (!HAS_BUN) console.warn("project-config.test.ts: skipping the real-bun sync test — `bun` is not on PATH");

describe.skipIf(!HAS_BUN)("real bun: sync, install, and the tree the install leaves is not drift", () => {
  test("generated lockfile → frozen install → probe present → no drift", { timeout: 120_000 }, () => {
    // Pin-free stand-ins: every package is a workspace, so no registry.
    const f = fixture({ base: "base", pins: false });
    const p = exampleProject(f);
    cleanups.push(p.cleanup);
    writeFileSync(join(p.project, "package.json"), '{"name":"example"}\n');
    expect(syncProjectConfig(p.project, f.harness).code).toBe(0);
    const install = spawnSync("bun", ["install", "--frozen-lockfile", "--ignore-scripts"], { cwd: p.project, encoding: "utf8" });
    expect(install.status, install.stderr).toBe(0);
    expect(existsSync(join(p.project, "node_modules", ".bun"))).toBe(true);
    expect(existsSync(join(p.project, "apps", "web", "node_modules", "@example", "project-management"))).toBe(true);
    expect(configDrift(p.project, f.harness)).toEqual([]);
  });
});
