import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, describe, expect, test } from "vitest";
import { readGuardLog } from "../../../src/guard-log.ts";
import { writeProjectPacks } from "../../../src/project-composition.ts";
import { applyInit, planInit } from "../../../src/project-init.ts";
import { BUILD_COMMAND, CHECK_BUILD_SCRIPT } from "../../ts-web/scripts/build-check.ts";
import { webAppPlan } from "../../ts-web/scripts/new-web-app.ts";
import { runDeliver, SURFACE_SCRIPT } from "./deliver.ts";
import { runDesignGate } from "./design-gate.ts";
import { runGreenGate } from "./green-gate.ts";
import { configDrift, configDriftBlock, generatedConfig, syncConfigCommand, syncProjectConfig } from "./project-config.ts";
import { packageFor } from "./project-package.ts";
import { runRedGate } from "./red-gate.ts";
import { runMutationScore } from "./mutation-score.ts";
import { runTests, runTestsGate } from "./run-tests.ts";
import { typecheck } from "./typecheck.ts";
import { typecheckGate } from "./typecheck-gate.ts";
import { renderScreenshot } from "../../ts-web/scripts/render-screenshot.ts";

const agentRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const packsDir = join(agentRoot, "packs");
const temporary: string[] = [];
afterAll(() => { for (const dir of temporary) rmSync(dir, { recursive: true, force: true }); });

/** A real project-local installation, as `bounded init` applies it. */
async function initialized(packs: readonly string[]): Promise<{ project: string; harness: string }> {
  const project = join(mkdtempSync(join(tmpdir(), "project-config-")), "app");
  temporary.push(dirname(project));
  const plan = await planInit(project, "claude-code", packs);
  await applyInit(project, "claude-code", packs, plan.digest);
  return { project, harness: join(project, ".bounded", "harness") };
}

/** A project whose packs have no initializer of their own (the ts pack
 *  alone), generated by the sync from nothing but the installation marker. */
function generatedBySync(packs: readonly string[]): { project: string; harness: string } {
  const project = mkdtempSync(join(tmpdir(), "project-config-sync-"));
  temporary.push(project);
  writeProjectPacks(project, packs);
  writeFileSync(join(project, ".bounded", "installation.json"), "{}\n");
  mkdirSync(join(project, "src"));
  expect(syncProjectConfig(project, agentRoot).code).toBe(0);
  return { project, harness: agentRoot };
}

const pkgOf = (project: string): { scripts: Record<string, string>; dependencies: Record<string, string>; devDependencies: Record<string, string> } =>
  JSON.parse(readFileSync(join(project, "package.json"), "utf8"));

const configFiles = (project: string, harness: string): string[] =>
  [...generatedConfig(project, harness).files.keys()].sort();

describe("project config is generated from the composed packs (ADR 2026-054)", () => {
  let tsOnly: { project: string; harness: string };
  let service: { project: string; harness: string };
  let web: { project: string; harness: string };

  test("an initialized project matches its packs exactly, judged by its own harness copy", async () => {
    tsOnly = generatedBySync(["ts"]);
    service = await initialized(["ts-service"]);
    web = await initialized(["ts-web"]);
    for (const { project, harness } of [tsOnly, service, web]) {
      expect(configDrift(project, harness)).toEqual([]);
      expect(configDriftBlock("red-gate", project, harness)).toBeUndefined();
    }
  }, 180_000);

  test("each composition generates its own files, and an uncomposed pack leaves no trace", () => {
    const surface = "scripts/surface-check.ts";
    expect(configFiles(tsOnly.project, tsOnly.harness)).toEqual(["package.json", surface, "tsconfig.json"]);
    expect(configFiles(service.project, service.harness)).toEqual(["package.json", surface, "tsconfig.api.json", "tsconfig.json"]);
    expect(configFiles(web.project, web.harness)).toEqual(["index.html", "package.json", surface, "tsconfig.json", "vite.config.ts"]);
    // The surface checker the generated check:surface runs is shipped at init,
    // byte-identical to the one delivery would ship.
    expect(readFileSync(join(service.project, surface), "utf8"))
      .toBe(readFileSync(join(packsDir, "ts", "scripts", "surface-check.ts"), "utf8"));
    expect(existsSync(join(tsOnly.project, "vite.config.ts"))).toBe(false);
    expect(existsSync(join(tsOnly.project, "tsconfig.api.json"))).toBe(false);
    expect(existsSync(join(service.project, "index.html"))).toBe(false);
    expect(existsSync(join(service.project, "vite.config.ts"))).toBe(false);

    const ts = pkgOf(tsOnly.project);
    expect(ts.scripts["check"]).toContain("npm run check:surface");
    expect(ts.scripts["check:build"]).toBeUndefined();
    expect(ts.devDependencies["ts-morph"]).toBeDefined();
    expect(ts.dependencies["@trpc/server"]).toBeUndefined();
    expect(ts.dependencies["react"]).toBeUndefined();
    expect(pkgOf(service.project).dependencies["@trpc/server"]).toBe("11.18.0");
    expect(pkgOf(service.project).scripts["check"]).not.toContain("check:build");
    const webPkg = pkgOf(web.project);
    expect(webPkg.scripts["check"]).toMatch(/npm run check:surface && npm run check:build$/);
    expect(webPkg.dependencies["react"]).toBeDefined();
    expect(webPkg.dependencies["@trpc/server"]).toBeUndefined();
  });

  test("a hand-edited manifest, compiler config or lockfile, and an extra test-runner config, are drift", () => {
    const { project, harness } = service;
    const pkg = pkgOf(project);
    pkg.devDependencies["left-pad"] = "1.3.0";
    writeFileSync(join(project, "package.json"), JSON.stringify(pkg, null, 2) + "\n");
    writeFileSync(join(project, "tsconfig.json"), readFileSync(join(project, "tsconfig.json"), "utf8").replace('"strict": true', '"strict": false'));
    writeFileSync(join(project, "vitest.config.ts"), "export default {};\n");
    const lock = JSON.parse(readFileSync(join(project, "package-lock.json"), "utf8")) as { packages: Record<string, unknown> };
    lock.packages["node_modules/left-pad"] = { version: "1.3.0" };
    writeFileSync(join(project, "package-lock.json"), JSON.stringify(lock, null, 2) + "\n");

    expect(configDrift(project, harness).map((d) => d.path).sort())
      .toEqual(["package-lock.json", "package.json", "tsconfig.json", "vitest.config.ts"]);
    expect(configDrift(project, harness).find((d) => d.path === "vitest.config.ts")?.problem).toMatch(/no composed pack generates it/);
  });

  test("the phase gates refuse drifted config before they run anything, routed to the orchestrator", async () => {
    const { project } = service;
    for (const [gate, result] of [
      ["design-gate", await runDesignGate(project)],
      ["red-gate", await runRedGate(project)],
      ["green-gate", await runGreenGate(project)],
    ] as const) {
      expect(result.code, gate).toBe(1);
      expect(result.lines, gate).toContain(`${gate}: route → orchestrator`);
      expect(result.lines.join("\n"), gate).toContain("bounded sync-config");
      expect(result.detail["step"], gate).toBe("config-drift");
    }
    const delivered = runDeliver(project, { run: () => { throw new Error("deliver ran a command over drifted config"); } });
    expect(delivered.code).toBe(1);
    expect(delivered.lines).toContain("deliver: route → orchestrator");
    expect(readGuardLog(project).filter((e) => (e.detail as { step?: unknown } | undefined)?.step === "config-drift").length).toBe(4);
  });

  test("sync restores every file, removes what no pack generates, and is then a no-op", () => {
    const { project, harness } = service;
    const first = syncProjectConfig(project, harness);
    expect(first.code).toBe(0);
    expect(first.lines).toContain("sync-config: removed vitest.config.ts (no composed pack generates it)");
    expect(existsSync(join(project, "vitest.config.ts"))).toBe(false);
    expect(configDrift(project, harness)).toEqual([]);
    expect(syncProjectConfig(project, harness).lines).toEqual(["sync-config: OK — project config already matches the composed packs"]);
  });

  test("sync writes the same manifest the initializer does", () => {
    const { project, harness } = web;
    rmSync(join(project, "package.json"));
    rmSync(join(project, "vite.config.ts"));
    expect(configDrift(project, harness).map((d) => d.path).sort()).toEqual(["package.json", "vite.config.ts"]);
    expect(syncProjectConfig(project, harness).code).toBe(0);
    expect(configDrift(project, harness)).toEqual([]);
    expect(readFileSync(join(project, "vite.config.ts"), "utf8"))
      .toBe(webAppPlan({ routerSpecifier: undefined }).find((f) => f.path === "vite.config.ts")!.content);
  });
});

describe("bounded sync-config reinstalls through the composed setup commands", () => {
  test("a sync that changed config runs the packs' setup commands; an unchanged, installed one runs nothing", async () => {
    const { project, harness } = await initialized(["ts-service"]);
    const ran: string[] = [];
    const run = (command: string, args: readonly string[], cwd: string): void => {
      ran.push([command, ...args].join(" "));
      mkdirSync(join(cwd, "node_modules"), { recursive: true });
      writeFileSync(join(cwd, "node_modules", ".package-lock.json"), "{}\n");
    };
    writeFileSync(join(project, "tsconfig.json"), "{}\n");
    const first = syncConfigCommand(project, harness, run);
    expect(first.code).toBe(0);
    expect(ran).toEqual(["npm ci --ignore-scripts"]);
    expect(first.lines).toContain("sync-config: ran npm ci --ignore-scripts");
    const second = syncConfigCommand(project, harness, run);
    expect(second.code).toBe(0);
    expect(ran).toHaveLength(1);
    const failing = syncConfigCommand(project, harness, () => { throw new Error("offline"); });
    expect(failing.code).toBe(0); // nothing changed and installed: nothing to run
    rmSync(join(project, "node_modules"), { recursive: true, force: true });
    const broken = syncConfigCommand(project, harness, () => { throw new Error("offline"); });
    expect(broken.code).toBe(1);
    expect(broken.lines.at(-1)).toMatch(/reinstall failed: npm ci --ignore-scripts/);
  }, 180_000);
});

describe("deliver never changes generated config", () => {
  test("a missing install or an unshipped checker is refused, not installed or written, and leaves no drift", async () => {
    const { project, harness } = await initialized(["ts-service"]);
    const noRun = (): never => { throw new Error("deliver ran npm in a generated project"); };
    const missing = runDeliver(project, { run: noRun });
    expect(missing.code).toBe(1);
    expect(missing.lines.join("\n")).toMatch(/ts-morph@\S+ is pinned but not installed/);
    expect(missing.lines).toContain("deliver: route → orchestrator");
    const stub = join(dirname(project), "stub-surface-check.ts");
    writeFileSync(stub, "// a different checker\n");
    const unshipped = runDeliver(project, { run: noRun, surfaceCheckSource: stub });
    expect(unshipped.code).toBe(1);
    expect(unshipped.lines.join("\n")).toMatch(/lacks what the surface check needs \(shipped scripts\/surface-check\.ts\)/);
    expect(configDrift(project, harness)).toEqual([]);
  }, 180_000);
});

describe("every tool that spawns the test runner or type-checker refuses drifted config first", () => {
  let web: { project: string; harness: string };
  const noSpawn = (): never => { throw new Error("spawned over drifted config"); };

  test("setup: an initialized web project with a test-runner config no pack generates", async () => {
    web = await initialized(["ts-web"]);
    writeFileSync(join(web.project, "vitest.config.ts"), "export default {};\n");
  }, 180_000);

  test("run-tests: the primitive and the gate", async () => {
    const raw = await runTests(web.project, { run: noSpawn });
    expect(raw.ok).toBe(false);
    expect(raw.blocked).toMatch(/config-drift: .*vitest\.config\.ts/);
    const gate = await runTestsGate(web.project, { run: noSpawn });
    expect(gate.code).toBe(1);
    expect(gate.lines).toContain("run_tests: route → orchestrator");
  });

  test("typecheck: the primitive and the gate", async () => {
    const raw = await typecheck(web.project, { run: noSpawn });
    expect(raw.ok).toBe(false);
    expect(raw.diagnostics.join("\n")).toMatch(/config-drift: .*vitest\.config\.ts/);
    const gate = await typecheckGate(web.project, "builder", { run: noSpawn });
    expect(gate.code).toBe(1);
    expect(gate.lines).toContain("typecheck: route → orchestrator");
  });

  test("mutation-score refuses before mutating a file", async () => {
    const r = await runMutationScore(web.project, { runSuite: noSpawn });
    expect(r.code).toBe(1);
    expect(r.lines).toContain("mutation-score: route → orchestrator");
  });

  test("the web render refuses before building", async () => {
    const r = await renderScreenshot(web.project, { run: noSpawn });
    expect(r.code).toBe(2);
    expect(r.lines).toContain("render-screenshot: route → orchestrator");
  });

  test("nested manifests and compiler configs are drift; installed dependencies' are not", () => {
    rmSync(join(web.project, "vitest.config.ts"));
    mkdirSync(join(web.project, "node_modules", "dep"), { recursive: true });
    writeFileSync(join(web.project, "node_modules", "dep", "package.json"), "{}\n");
    expect(configDrift(web.project, web.harness)).toEqual([]);
    mkdirSync(join(web.project, "tests", "unit"), { recursive: true });
    writeFileSync(join(web.project, "src", "ui", "package.json"), '{"type":"commonjs"}\n');
    writeFileSync(join(web.project, "tests", "unit", "tsconfig.json"), "{}\n");
    expect(configDrift(web.project, web.harness).map((d) => d.path))
      .toEqual(["src/ui/package.json", "tests/unit/tsconfig.json"]);
    const sync = syncProjectConfig(web.project, web.harness);
    expect(sync.lines).toContain("sync-config: removed src/ui/package.json (no composed pack generates it)");
    expect(configDrift(web.project, web.harness)).toEqual([]);
    expect(existsSync(join(web.project, "node_modules", "dep", "package.json"))).toBe(true);
  });

  test("a dependency directory, .git or .bounded below the root is drift, whatever it holds", () => {
    for (const dir of ["src/node_modules/zod", "tests/Node_Modules", "src/.bounded", "src/lib/.GIT"]) {
      mkdirSync(join(web.project, dir), { recursive: true });
    }
    writeFileSync(join(web.project, "src", "node_modules", "zod", "index.d.ts"), "export {};\n");
    expect(configDrift(web.project, web.harness).map((d) => d.path))
      .toEqual(["src/.bounded", "src/lib/.GIT", "src/node_modules", "tests/Node_Modules"]);
    const sync = syncProjectConfig(web.project, web.harness);
    expect(sync.lines).toContain("sync-config: removed src/node_modules (no composed pack generates it)");
    expect(configDrift(web.project, web.harness)).toEqual([]);
    expect(existsSync(join(web.project, "node_modules", "dep", "package.json"))).toBe(true);
  });

  test("pi's own package installs are the host's, not drift; the rest of .pi is still walked", () => {
    for (const dir of [".pi/npm/node_modules/pi-subagents", ".pi/git/example/node_modules", ".pi/extensions/node_modules"]) {
      mkdirSync(join(web.project, dir), { recursive: true });
    }
    writeFileSync(join(web.project, ".pi", "npm", "package.json"), "{}\n");
    writeFileSync(join(web.project, ".pi", "npm", "node_modules", "pi-subagents", "package.json"), "{}\n");
    expect(configDrift(web.project, web.harness).map((d) => d.path)).toEqual([".pi/extensions/node_modules"]);
    syncProjectConfig(web.project, web.harness);
    expect(configDrift(web.project, web.harness)).toEqual([]);
    expect(existsSync(join(web.project, ".pi", "npm", "package.json"))).toBe(true);
  });
});

describe("where the drift check does not apply", () => {
  test("a project not initialized by bounded init has no generated config to compare", () => {
    const project = mkdtempSync(join(tmpdir(), "project-config-legacy-"));
    temporary.push(project);
    writeProjectPacks(project, ["ts"]);
    writeFileSync(join(project, "package.json"), "{}\n");
    writeFileSync(join(project, "vitest.config.ts"), "export default {};\n");
    expect(configDriftBlock("green-gate", project)).toBeUndefined();
    const sync = syncProjectConfig(project);
    expect(sync.code).toBe(1);
    expect(readFileSync(join(project, "package.json"), "utf8")).toBe("{}\n");
  });

  test("an unreadable composition in a generated project is a block, not a pass", () => {
    const project = mkdtempSync(join(tmpdir(), "project-config-broken-"));
    temporary.push(project);
    mkdirSync(join(project, ".bounded"));
    writeFileSync(join(project, ".bounded", "installation.json"), "{}\n");
    const block = configDriftBlock("red-gate", project);
    expect(block?.code).toBe(1);
    expect(block?.lines.join("\n")).toMatch(/cannot be computed/);
  });
});

describe("pack data mirrors what delivery and the generators write", () => {
  test("the generated manifest is already the delivered one", () => {
    const pkg = packageFor(["ts", "ts-web"], packsDir);
    expect(pkg.scripts!["check:surface"]).toBe(SURFACE_SCRIPT);
    expect(pkg.scripts![CHECK_BUILD_SCRIPT]).toBe(BUILD_COMMAND);
    const harness = JSON.parse(readFileSync(join(agentRoot, "package.json"), "utf8")) as { devDependencies: Record<string, string> };
    expect(pkg.devDependencies!["ts-morph"]).toBe(harness.devDependencies["ts-morph"]);
  });

  test("ts-web's reference vite config and html entry are byte-identical to the generator's", () => {
    for (const path of ["vite.config.ts", "index.html"]) {
      expect(readFileSync(join(packsDir, "ts-web", "reference", path), "utf8"), path)
        .toBe(webAppPlan({ routerSpecifier: undefined }).find((f) => f.path === path)!.content);
    }
  });
});
