// The project initializer of the adapter and app packs (bounded init).
//
// In the hexagonal monorepo nothing app-shaped exists before the design: a TN
// declares each app (`workspaces:`), the design gate seeds its files from the
// contracts, and the config sync writes its manifest (ADR LEG-2026-061). So init
// seeds one file, `apps/README.md`, which says exactly that to the next reader.
//
// The same text is seeded by ts-trpc, ts-mcp and ts-lambda (byte-identical
// copies of this file, held together by in-adapter-kit.test.ts) and by ts-web
// and ts-desktop (which import this one across their edge to ts-trpc), so any
// selection is covered and two initializers in one selection agree.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { isMainModule } from "../../../src/is-main-module.ts";

export const APPS_README = "apps/README.md";
export const APPS_README_CONTENT = [
  "# Apps",
  "",
  "<!-- GENERATED by bounded init — do not edit. -->",
  "",
  "Each app is a workspace declared in a ticket TN's front matter, for example",
  "`workspaces:` then `  apps/web: web`. The design gate seeds its files from the",
  "design, and `bounded sync-config` writes its package.json.",
  "",
].join("\n");

export function seedApps(target: string): void {
  const path = join(target, APPS_README);
  if (existsSync(path)) {
    if (readFileSync(path, "utf8") !== APPS_README_CONTENT) throw new Error(`${APPS_README} already contains project work`);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, APPS_README_CONTENT);
}

if (isMainModule(import.meta.url)) {
  seedApps(resolve(process.argv[2] ?? process.cwd()));
}
