// Generated by the ts-drizzle-sqlite capability; no role edits it (ADR 2026-055).
// The migration check sets BOUNDED_DRIZZLE_OUT to generate into a temporary
// copy, so the check never writes the project's migrations.
import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: "./src/db/schema.ts",
  out: process.env.BOUNDED_DRIZZLE_OUT ?? "./migrations",
  dialect: "sqlite",
  dbCredentials: { url: process.env.DATABASE_URL ?? "file:./data/app.sqlite" },
});
