/** Project-local pi wiring. The caller stages the copied harness before invoking this. */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";

const EXTENSIONS = ["architect-tools", "dev-tools", "model-tier", "path-gate", "web"] as const;
const ROLE_EXTENSION = /subagentOnlyExtensions: ~\/\.pi\/agent\/hosts\/pi\/extensions\/path-gate\/([\w-]+\.ts)/g;

/** A path written into the project must not depend on the installer's location. */
function localPath(from: string, to: string): string {
  const path = relative(from, to).split(sep).join("/");
  return path.startsWith(".") ? path : `./${path}`;
}

function putNew(path: string, content: string): void {
  if (existsSync(path)) throw new Error(`pi project install refused existing file: ${path}`);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

/**
 * Bind only the selected pi host to a staged project. Common copying,
 * ownership, and publication are the init core's responsibility.
 */
export function installProjectPi(target: string, harnessRoot: string): void {
  const project = resolve(target);
  const harness = resolve(harnessRoot);
  if (!harness.startsWith(`${project}${sep}`)) {
    throw new Error("pi project install requires a harness copy inside the project");
  }

  const extensionDir = join(harness, "hosts", "pi", "extensions");
  const agentDir = join(harness, "agents");
  const skillDir = join(harness, "skills");
  const bootstrapSource = join(harness, "hosts", "pi", "bootstrap.ts");
  for (const path of [...EXTENSIONS.map((name) => join(extensionDir, `${name}.ts`)), bootstrapSource, agentDir, skillDir]) {
    if (!existsSync(path)) throw new Error(`pi project install missing copied harness resource: ${path}`);
  }

  const loader = join(project, ".pi", "extensions", "bounded", "index.ts");
  const settings = join(project, ".pi", "settings.json");
  const roles = readdirSync(agentDir).filter((name) => name.endsWith(".md")).sort();
  const destinations = [loader, settings, ...roles.map((name) => join(project, ".pi", "agents", name))];
  for (const path of destinations) {
    if (existsSync(path)) throw new Error(`pi project install refused existing file: ${path}`);
  }

  // The loader and the bootstrap it imports use only Node builtins at
  // runtime. A fresh clone has no local packages yet, so the full adapter is
  // imported only after setup has made its dependencies ready.
  const imports = EXTENSIONS.map((name) =>
    `    import(${JSON.stringify(localPath(dirname(loader), join(extensionDir, `${name}.ts`)))}),`,
  );
  const loaderText = [
    "// Generated by Bounded. Dependency-free bootstrap, then the full adapter.",
    'import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";',
    'import { dirname, resolve } from "node:path";',
    'import { fileURLToPath } from "node:url";',
    `import { enterProject } from ${JSON.stringify(localPath(dirname(loader), bootstrapSource))};`,
    "",
    `const project = resolve(dirname(fileURLToPath(import.meta.url)), ${JSON.stringify(relative(dirname(loader), project).split(sep).join("/"))});`,
    "",
    "export default function (pi: ExtensionAPI): Promise<void> {",
    "  return enterProject(pi, project, () => Promise.all([",
    ...imports,
    "  ]));",
    "}",
    "",
  ].join("\n");

  const settingsText = JSON.stringify({
    packages: ["npm:pi-subagents@0.52.1"],
    skills: [localPath(dirname(settings), skillDir), localPath(dirname(settings), join(harness, "packs"))],
    subagents: { disableBuiltins: true },
  }, null, 2) + "\n";

  const renderedRoles = roles.map((name) => {
    const source = readFileSync(join(agentDir, name), "utf8");
    const content = source.replace(ROLE_EXTENSION, (_match, roleFile: string) => {
      const roleExtension = join(extensionDir, "path-gate", roleFile);
      if (!existsSync(roleExtension)) throw new Error(`pi project install missing role extension: ${roleExtension}`);
      return `subagentOnlyExtensions: ${localPath(project, roleExtension)}`;
    });
    if (content.includes("~/.pi/agent/")) {
      throw new Error(`pi project install cannot render global path in ${name}`);
    }
    return { path: join(project, ".pi", "agents", name), content };
  });

  putNew(loader, loaderText);
  putNew(settings, settingsText);
  for (const role of renderedRoles) putNew(role.path, role.content);
}
