// Generated by the ts-hexagonal pack; do not edit. The rules are in
// docs/architecture/layers-and-dependencies.md and bounded-contexts.md.
//
// Every import of every source file under contexts/*/src and apps/*/src is
// read with the TypeScript parser, so no import form slips past: static,
// side-effect, re-export, `import x = require()`, `require()`, dynamic
// `import()` and `import("…").Type`, with either quote style.
import { describe, expect, test } from "bun:test";
import { Glob } from "bun";
import * as ts from "typescript";

const ROOT = import.meta.dir;
const KEBAB = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;

type Rule = "layers" | "placement" | "contexts" | "apps" | "browser" | "in-adapters";

interface Violation {
  readonly rule: Rule;
  readonly text: string;
}

interface Workspace {
  readonly kind: "context" | "app";
  readonly name: string;
  readonly dir: string;
}

type Location =
  | { kind: "context"; name: string; dir: string; inner: string[]; layer: "domain" | "application" | "adapters-in" | "adapters-out" | "none"; tech?: string }
  | { kind: "app"; name: string; dir: string; inner: string[]; browser: boolean };

interface Use {
  readonly spec: string | undefined;
  readonly line: number;
  /** `import type` / `export type` / `import("x").T`: erased at runtime. */
  readonly typeOnly: boolean;
  /** `import { type A }`: every name is a type, but the module still loads. */
  readonly inlineTypes: boolean;
  readonly names: readonly string[];
  /** A member read off a namespace import (`App.CreateNoteHandler`). */
  readonly member?: true;
}

function locate(path: string): Location | undefined {
  const segments = path.split("/");
  if (segments.length < 4 || segments[2] !== "src" || (segments[0] !== "contexts" && segments[0] !== "apps")) return undefined;
  const name = segments[1]!;
  const dir = `${segments[0]}/${name}`;
  const inner = segments.slice(3);
  if (segments[0] === "apps") {
    return { kind: "app", name, dir, inner, browser: inner.length > 1 && (inner[0] === "client" || inner[0] === "renderer") };
  }
  if (inner.length > 1 && inner[0] === "domain") return { kind: "context", name, dir, inner, layer: "domain" };
  if (inner.length > 1 && inner[0] === "application") return { kind: "context", name, dir, inner, layer: "application" };
  if (inner.length > 3 && inner[0] === "adapters" && (inner[1] === "in" || inner[1] === "out")) {
    return { kind: "context", name, dir, inner, layer: inner[1] === "in" ? "adapters-in" : "adapters-out", tech: inner[2] };
  }
  return { kind: "context", name, dir, inner, layer: "none" };
}

function joinPath(fromDir: string, spec: string): string | undefined {
  const out = fromDir.split("/");
  for (const segment of spec.split("/")) {
    if (segment === "" || segment === ".") continue;
    if (segment === "..") {
      if (out.length === 0) return undefined;
      out.pop();
    } else out.push(segment);
  }
  return out.join("/");
}

function packageOf(spec: string): { name: string; subpath: string } | undefined {
  const parts = spec.split("/");
  if (spec.startsWith("@")) return parts.length < 2 ? undefined : { name: `${parts[0]}/${parts[1]}`, subpath: parts.slice(2).join("/") };
  return { name: parts[0]!, subpath: parts.slice(1).join("/") };
}

const isTestSide = (path: string): boolean => /\.(test\.tsx?|test-support\.ts)$/i.test(path);
const isExportPath = (subpath: string): boolean =>
  subpath === "domain" || subpath === "application" || /^adapters\/[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(subpath);

function usesOf(path: string, text: string): Use[] {
  const file = ts.createSourceFile(path, text, ts.ScriptTarget.Latest, true, path.endsWith("x") ? ts.ScriptKind.TSX : ts.ScriptKind.TS);
  const out: Use[] = [];
  const namespaces = new Map<string, number>();
  const lineOf = (node: ts.Node): number => file.getLineAndCharacterOfPosition(node.getStart(file)).line + 1;
  const literal = (node: ts.Node | undefined): string | undefined =>
    node !== undefined && (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) ? node.text : undefined;
  const push = (node: ts.Node, spec: string | undefined, typeOnly: boolean, names: string[] = [], inlineTypes = false): void => {
    out.push({ spec, line: lineOf(node), typeOnly, inlineTypes, names });
  };
  const visit = (node: ts.Node): void => {
    if (ts.isImportDeclaration(node)) {
      const clause = node.importClause;
      const names: string[] = [];
      let inlineTypes = false;
      if (clause?.name !== undefined) names.push(clause.name.text);
      const bindings = clause?.namedBindings;
      if (bindings !== undefined && ts.isNamedImports(bindings)) {
        for (const element of bindings.elements) names.push((element.propertyName ?? element.name).text);
        inlineTypes = clause?.name === undefined && bindings.elements.length > 0 && bindings.elements.every((e) => e.isTypeOnly);
      }
      if (bindings !== undefined && ts.isNamespaceImport(bindings)) namespaces.set(bindings.name.text, 0);
      push(node, literal(node.moduleSpecifier), clause?.isTypeOnly === true, names, inlineTypes);
    } else if (ts.isExportDeclaration(node) && node.moduleSpecifier !== undefined) {
      const names = node.exportClause !== undefined && ts.isNamedExports(node.exportClause)
        ? node.exportClause.elements.map((e) => (e.propertyName ?? e.name).text)
        : [];
      const inlineTypes = node.exportClause !== undefined && ts.isNamedExports(node.exportClause) &&
        node.exportClause.elements.length > 0 && node.exportClause.elements.every((e) => e.isTypeOnly);
      push(node, literal(node.moduleSpecifier), node.isTypeOnly, names, inlineTypes);
    } else if (ts.isImportEqualsDeclaration(node) && ts.isExternalModuleReference(node.moduleReference)) {
      push(node, literal(node.moduleReference.expression), node.isTypeOnly, [node.name.text]);
    } else if (ts.isCallExpression(node) &&
      (node.expression.kind === ts.SyntaxKind.ImportKeyword || (ts.isIdentifier(node.expression) && node.expression.text === "require"))) {
      push(node, literal(node.arguments[0]), false);
    } else if (ts.isImportTypeNode(node)) {
      const argument = ts.isLiteralTypeNode(node.argument) ? literal(node.argument.literal) : undefined;
      push(node, argument, true, node.qualifier === undefined ? [] : [node.qualifier.getText(file).split(".").pop()!]);
    } else if (ts.isPropertyAccessExpression(node) && ts.isIdentifier(node.expression) && namespaces.has(node.expression.text)) {
      out.push({ spec: node.expression.text, line: lineOf(node), typeOnly: true, inlineTypes: false, names: [node.name.text], member: true });
    } else if (ts.isQualifiedName(node) && ts.isIdentifier(node.left) && namespaces.has(node.left.text)) {
      out.push({ spec: node.left.text, line: lineOf(node), typeOnly: true, inlineTypes: false, names: [node.right.text], member: true });
    }
    ts.forEachChild(node, visit);
  };
  visit(file);
  return out;
}

async function workspaces(): Promise<Map<string, Workspace>> {
  const out = new Map<string, Workspace>();
  for await (const manifest of new Glob("{contexts,apps}/*/package.json").scan({ cwd: ROOT })) {
    const [root, name] = manifest.split("/") as [string, string];
    const pkg = (await Bun.file(`${ROOT}/${manifest}`).json()) as { name?: unknown };
    if (typeof pkg.name === "string") out.set(pkg.name, { kind: root === "contexts" ? "context" : "app", name, dir: `${root}/${name}` });
  }
  return out;
}

async function sourceFiles(): Promise<string[]> {
  const files: string[] = [];
  for await (const path of new Glob("{contexts,apps}/*/src/**/*.{ts,tsx,mts,cts}").scan({ cwd: ROOT })) {
    if (!path.split("/").includes("node_modules")) files.push(path);
  }
  return files.sort();
}

async function sourceRoots(): Promise<string[]> {
  const roots: string[] = [];
  for await (const path of new Glob("{contexts,apps}/*/src/**").scan({ cwd: ROOT, onlyFiles: false })) {
    const root = path.split("/").slice(0, 3).join("/");
    if (!roots.includes(root)) roots.push(root);
  }
  return roots;
}

const LAYER_ALLOWS: Readonly<Record<string, readonly string[]>> = {
  domain: ["domain"],
  application: ["domain", "application"],
  "adapters-in": ["domain", "application", "adapters-in"],
  "adapters-out": ["domain", "application", "adapters-out"],
};

function checkContextUse(file: string, from: Extract<Location, { kind: "context" }>, use: Use, index: Map<string, Workspace>): Violation[] {
  const spec = use.spec!;
  const at = `${file}:${use.line} imports "${spec}"`;
  const v = (rule: Rule, why: string): Violation[] => [{ rule, text: `${at} — ${why}` }];
  const test = isTestSide(file);
  if (spec.startsWith(".")) {
    const target = joinPath(file.split("/").slice(0, -1).join("/"), spec);
    const to = target === undefined ? undefined : locate(target);
    if (to === undefined) return v("layers", "it reaches outside every source root");
    if (to.dir !== from.dir) return v("contexts", `it reaches into ${to.dir} by a relative path; contexts never import each other or an app`);
    if (to.kind !== "context" || to.layer === "none") return v("layers", "its target sits in no layer");
    if (!LAYER_ALLOWS[from.layer]!.includes(to.layer)) {
      return v("layers", `${from.layer} may not depend on ${to.layer}; dependencies point inwards: domain <- application <- adapters`);
    }
    if (from.tech !== undefined && to.tech !== undefined && (from.tech !== to.tech || from.layer !== to.layer)) {
      return v("layers", `adapters never import other adapters (${from.layer}/${from.tech} -> ${to.layer}/${to.tech})`);
    }
    return [];
  }
  if (spec.startsWith("/")) return v("layers", "absolute paths are not allowed");
  const pkg = packageOf(spec);
  const workspace = pkg === undefined ? undefined : index.get(pkg.name);
  if (workspace !== undefined) {
    if (workspace.kind === "app") return v("contexts", "contexts never import an app");
    if (workspace.dir !== from.dir) {
      if (from.layer === "adapters-out" && pkg!.subpath === "application") return [];
      return v("contexts", "contexts never import each other; only an out adapter may call another context's application");
    }
    if (!isExportPath(pkg!.subpath)) return v("layers", "import a package only through its export paths (domain, application, adapters/<tech>)");
    const toLayer = pkg!.subpath === "domain" ? "domain" : pkg!.subpath === "application" ? "application" : "adapters";
    const inwards = `${from.layer} may not depend on ${toLayer}; dependencies point inwards: domain <- application <- adapters`;
    if (from.layer === "domain") {
      return v("layers", toLayer === "domain" ? "domain files import each other by relative path, never through the package" : inwards);
    }
    if (from.layer === "application" && toLayer !== "domain") {
      return v("layers", toLayer === "application" ? "application files import their own feature's files by relative path" : inwards);
    }
    if (toLayer === "adapters") return v("layers", "adapters never import other adapters");
    return [];
  }
  if ((from.layer === "domain" || from.layer === "application") && !test && spec !== "zod" && !spec.startsWith("zod/")) {
    return v("layers", `${from.layer} code may use no library but zod: it holds no I/O and no framework`);
  }
  return [];
}

function checkAppUse(file: string, from: Extract<Location, { kind: "app" }>, use: Use, index: Map<string, Workspace>): Violation[] {
  const spec = use.spec!;
  const at = `${file}:${use.line} imports "${spec}"`;
  const out: Violation[] = [];
  let server = false;
  if (spec.startsWith(".")) {
    const target = joinPath(file.split("/").slice(0, -1).join("/"), spec);
    const to = target === undefined ? undefined : locate(target);
    if (to === undefined || to.dir !== from.dir) {
      out.push({ rule: "apps", text: `${at} — an app reaches only its own src/ by relative path; other workspaces through their packages` });
    } else if (from.browser && to.inner[0] !== from.inner[0]) {
      server = true;
    }
  } else if (spec.startsWith("/")) {
    out.push({ rule: "apps", text: `${at} — absolute paths are not allowed` });
  } else {
    const pkg = packageOf(spec);
    const workspace = pkg === undefined ? undefined : index.get(pkg.name);
    if (workspace?.kind === "app") out.push({ rule: "apps", text: `${at} — apps never import other apps` });
    if (workspace?.kind === "context") {
      server = true;
      if (!isExportPath(pkg!.subpath)) {
        out.push({ rule: "apps", text: `${at} — import a context only through its export paths (domain, application, adapters/<tech>)` });
      }
    }
  }
  if (from.browser && server && !use.typeOnly) {
    out.push({
      rule: "browser",
      text: use.inlineTypes
        ? `${at} — 'import { type … }' still loads the module in the browser; write 'import type { … }'`
        : `${at} — browser code imports server code as types only ('import type')`,
    });
  }
  return out;
}

async function check(): Promise<{ files: string[]; roots: string[]; violations: Violation[] }> {
  const index = await workspaces();
  const files = await sourceFiles();
  const violations: Violation[] = [];
  for (const file of files) {
    const from = locate(file)!;
    if (from.kind === "context" && from.layer === "none") {
      violations.push({ rule: "placement", text: `${file} — every context file sits in domain/, application/ or adapters/in|out/<tech>/` });
      continue;
    }
    for (const use of usesOf(file, await Bun.file(`${ROOT}/${file}`).text())) {
      if (use.spec === undefined) {
        violations.push({ rule: "layers", text: `${file}:${use.line} — an import with a computed specifier cannot be checked` });
        continue;
      }
      if (from.kind === "context" && from.layer === "adapters-in" &&
        (use.names.some((n) => /Handler$/.test(n)) || (use.member !== true && /\.handler(\.[cm]?[jt]s)?$/.test(use.spec)))) {
        violations.push({
          rule: "in-adapters",
          text: `${file}:${use.line} uses "${use.names.find((n) => /Handler$/.test(n)) ?? use.spec}" — in adapters depend on in-port interfaces, never on handler classes`,
        });
      }
      if (use.member === true) continue;
      violations.push(...(from.kind === "context" ? checkContextUse(file, from, use, index) : checkAppUse(file, from, use, index)));
    }
  }
  return { files, roots: await sourceRoots(), violations };
}

const result = await check();
const of = (rule: Rule): string[] => result.violations.filter((v) => v.rule === rule).map((v) => v.text);

describe("architecture", () => {
  test("the scan reads every source root that holds files", () => {
    expect(result.roots.length === 0 || result.files.length > 0).toBe(true);
  });

  test("every context file sits in a layer", () => {
    expect(of("placement")).toEqual([]);
  });

  test("dependencies point inwards: domain <- application <- adapters", () => {
    expect(of("layers")).toEqual([]);
  });

  test("contexts never import each other or an app", () => {
    expect(of("contexts")).toEqual([]);
  });

  test("apps import contexts only through their export paths, and never each other", () => {
    expect(of("apps")).toEqual([]);
  });

  test("browser code imports server code as types only", () => {
    expect(of("browser")).toEqual([]);
  });

  test("in adapters depend on in ports, never on handler classes", () => {
    expect(of("in-adapters")).toEqual([]);
  });

  test("workspace directories are kebab-case", () => {
    const bad = result.roots.map((r) => r.split("/")[1]!).filter((n) => !KEBAB.test(n));
    expect(bad).toEqual([]);
  });
});
