// Generated by the ts-hexagonal pack; do not edit. The rules are in
// docs/architecture/layers-and-dependencies.md and bounded-contexts.md.
//
// Every import of every source file under contexts/*/src and apps/*/src
// (TypeScript and JavaScript, dot-files included) is read with the TypeScript
// parser, so no import form slips past: static, side-effect, re-export,
// `import x = require()`, `require()`, `require.resolve()`, dynamic
// `import()`, `import.meta.require()` / `resolve()` and `import("…").Type`,
// with either quote style. Domain and application code is also read for the
// runtime globals that reach I/O without an import.
import { describe, expect, test } from "bun:test";
import { Glob } from "bun";
import { readdirSync, statSync } from "node:fs";
import * as ts from "typescript";

const ROOT = import.meta.dir;
const KEBAB = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;

type Rule = "layers" | "placement" | "contexts" | "apps" | "browser" | "in-adapters" | "wiring" | "io";

/** How a module is reached: by name, as a whole, or loaded at runtime. */
type Form = "named" | "default" | "namespace" | "export-all" | "loader" | "member";
const CODE = /\.(ts|tsx|mts|cts|js|jsx|mjs|cjs)$/;

interface Violation {
  readonly rule: Rule;
  readonly text: string;
}

interface Workspace {
  readonly kind: "context" | "app";
  readonly name: string;
  readonly dir: string;
}

type Location =
  | { kind: "context"; name: string; dir: string; inner: string[]; layer: "domain" | "application" | "adapters-in" | "adapters-out" | "none"; tech?: string }
  | { kind: "app"; name: string; dir: string; inner: string[]; browser: boolean };

interface Use {
  readonly spec: string | undefined;
  readonly line: number;
  /** `import type` / `export type` / `import("x").T`: erased at runtime. */
  readonly typeOnly: boolean;
  /** `import { type A }`: every name is a type, but the module still loads. */
  readonly inlineTypes: boolean;
  readonly names: readonly string[];
  /** `member`: a name read off a namespace import (`App.CreateNoteHandler`). */
  readonly form: Form;
}

function locate(path: string): Location | undefined {
  const segments = path.split("/");
  if (segments.length < 4 || segments[2] !== "src" || (segments[0] !== "contexts" && segments[0] !== "apps")) return undefined;
  const name = segments[1]!;
  const dir = `${segments[0]}/${name}`;
  const inner = segments.slice(3);
  if (segments[0] === "apps") {
    return { kind: "app", name, dir, inner, browser: inner.length > 1 && (inner[0] === "client" || inner[0] === "renderer") };
  }
  if (inner.length > 1 && inner[0] === "domain") return { kind: "context", name, dir, inner, layer: "domain" };
  if (inner.length > 1 && inner[0] === "application") return { kind: "context", name, dir, inner, layer: "application" };
  if (inner.length > 3 && inner[0] === "adapters" && (inner[1] === "in" || inner[1] === "out")) {
    return { kind: "context", name, dir, inner, layer: inner[1] === "in" ? "adapters-in" : "adapters-out", tech: inner[2] };
  }
  return { kind: "context", name, dir, inner, layer: "none" };
}

function joinPath(fromDir: string, spec: string): string | undefined {
  const out = fromDir.split("/");
  for (const segment of spec.split("/")) {
    if (segment === "" || segment === ".") continue;
    if (segment === "..") {
      if (out.length === 0) return undefined;
      out.pop();
    } else out.push(segment);
  }
  return out.join("/");
}

function packageOf(spec: string): { name: string; subpath: string } | undefined {
  const parts = spec.split("/");
  if (spec.startsWith("@")) return parts.length < 2 ? undefined : { name: `${parts[0]}/${parts[1]}`, subpath: parts.slice(2).join("/") };
  return { name: parts[0]!, subpath: parts.slice(1).join("/") };
}

/** Test-side file names: the harness's composed test suffixes, the same list
 *  its lint rules and gates use. Matching ignores case. */
const TEST_SUFFIXES = [".test.ts", ".test.tsx", ".spec.ts", ".spec.tsx", "_test.ts", "_test.tsx", "_spec.ts", "_spec.tsx", ".test-support.ts"];
const isTestSide = (path: string): boolean => TEST_SUFFIXES.some((suffix) => path.toLowerCase().endsWith(suffix));
const isCompositionRoot = (path: string): boolean => /(^|\/)composition-root\.ts$/.test(path);
const WHOLE_MODULE: readonly Form[] = ["default", "namespace", "export-all", "loader"];

/** Does an import reach application or adapter code of some context? */
function wiringTarget(file: string, spec: string, index: Map<string, Workspace>): "application" | "adapters" | undefined {
  if (spec.startsWith(".")) {
    const target = joinPath(file.split("/").slice(0, -1).join("/"), spec);
    const to = target === undefined ? undefined : locate(target);
    if (to?.kind !== "context") return undefined;
    if (to.layer === "application") return "application";
    return to.layer === "adapters-in" || to.layer === "adapters-out" ? "adapters" : undefined;
  }
  const pkg = packageOf(spec);
  const workspace = pkg === undefined ? undefined : index.get(pkg.name);
  if (workspace?.kind !== "context") return undefined;
  if (pkg!.subpath === "application") return "application";
  return pkg!.subpath.startsWith("adapters/") ? "adapters" : undefined;
}
const isExportPath = (subpath: string): boolean =>
  subpath === "domain" || subpath === "application" || /^adapters\/[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(subpath);

function scriptKind(path: string): ts.ScriptKind {
  if (/\.tsx$/.test(path)) return ts.ScriptKind.TSX;
  if (/\.jsx$/.test(path)) return ts.ScriptKind.JSX;
  if (/\.[cm]?js$/.test(path)) return ts.ScriptKind.JS;
  return ts.ScriptKind.TS;
}

function usesOf(path: string, text: string): Use[] {
  const file = ts.createSourceFile(path, text, ts.ScriptTarget.Latest, true, scriptKind(path));
  const out: Use[] = [];
  const namespaces = new Set<string>();
  const lineOf = (node: ts.Node): number => file.getLineAndCharacterOfPosition(node.getStart(file)).line + 1;
  const literal = (node: ts.Node | undefined): string | undefined =>
    node !== undefined && (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) ? node.text : undefined;
  const push = (node: ts.Node, spec: string | undefined, form: Form, typeOnly: boolean, names: string[] = [], inlineTypes = false): void => {
    out.push({ spec, line: lineOf(node), form, typeOnly, inlineTypes, names });
  };
  /** `import(…)`, `require(…)`, `require.resolve(…)`, `import.meta.require(…)`, `import.meta.resolve(…)`. */
  const isLoader = (callee: ts.Expression): boolean => {
    if (callee.kind === ts.SyntaxKind.ImportKeyword) return true;
    if (ts.isIdentifier(callee)) return callee.text === "require";
    if (!ts.isPropertyAccessExpression(callee)) return false;
    const object = callee.expression;
    const name = callee.name.text;
    if (ts.isIdentifier(object) && object.text === "require") return name === "resolve";
    if (ts.isIdentifier(object) && object.text === "module") return name === "require";
    return ts.isMetaProperty(object) && object.keywordToken === ts.SyntaxKind.ImportKeyword && (name === "require" || name === "resolve");
  };
  const visit = (node: ts.Node): void => {
    if (ts.isImportDeclaration(node)) {
      const clause = node.importClause;
      const names: string[] = [];
      let inlineTypes = false;
      let form: Form = "named";
      if (clause?.name !== undefined) {
        names.push("default");
        form = "default";
      }
      const bindings = clause?.namedBindings;
      if (bindings !== undefined && ts.isNamedImports(bindings)) {
        for (const element of bindings.elements) names.push((element.propertyName ?? element.name).text);
        inlineTypes = clause?.name === undefined && bindings.elements.length > 0 && bindings.elements.every((e) => e.isTypeOnly);
      }
      if (bindings !== undefined && ts.isNamespaceImport(bindings)) {
        namespaces.add(bindings.name.text);
        form = "namespace";
      }
      push(node, literal(node.moduleSpecifier), form, clause?.isTypeOnly === true, names, inlineTypes);
    } else if (ts.isExportDeclaration(node) && node.moduleSpecifier !== undefined) {
      const clause = node.exportClause;
      const names = clause !== undefined && ts.isNamedExports(clause) ? clause.elements.map((e) => (e.propertyName ?? e.name).text) : [];
      const inlineTypes = clause !== undefined && ts.isNamedExports(clause) && clause.elements.length > 0 && clause.elements.every((e) => e.isTypeOnly);
      push(node, literal(node.moduleSpecifier), clause === undefined || ts.isNamespaceExport(clause) ? "export-all" : "named",
        node.isTypeOnly, names, inlineTypes);
    } else if (ts.isImportEqualsDeclaration(node) && ts.isExternalModuleReference(node.moduleReference)) {
      push(node, literal(node.moduleReference.expression), "loader", node.isTypeOnly, [node.name.text]);
    } else if (ts.isCallExpression(node) && isLoader(node.expression)) {
      push(node, literal(node.arguments[0]), "loader", false);
    } else if (ts.isImportTypeNode(node)) {
      const argument = ts.isLiteralTypeNode(node.argument) ? literal(node.argument.literal) : undefined;
      push(node, argument, "named", true, node.qualifier === undefined ? [] : [node.qualifier.getText(file).split(".").pop()!]);
    } else if (ts.isPropertyAccessExpression(node) && ts.isIdentifier(node.expression) && namespaces.has(node.expression.text)) {
      out.push({ spec: node.expression.text, line: lineOf(node), form: "member", typeOnly: true, inlineTypes: false, names: [node.name.text] });
    } else if (ts.isQualifiedName(node) && ts.isIdentifier(node.left) && namespaces.has(node.left.text)) {
      out.push({ spec: node.left.text, line: lineOf(node), form: "member", typeOnly: true, inlineTypes: false, names: [node.right.text] });
    }
    ts.forEachChild(node, visit);
  };
  visit(file);
  return out;
}

/** Modules (with or without `node:`, and their subpaths) that do I/O. */
function isIoModule(spec: string): boolean {
  if (spec === "bun" || spec.startsWith("bun:") || spec.startsWith("bun/")) return true;
  const bare = spec.startsWith("node:") ? spec.slice("node:".length) : spec;
  return ["fs", "child_process", "net"].some((name) => bare === name || bare.startsWith(`${name}/`));
}

/** The runtime globals, and the members of each that reach I/O. */
const IO_MEMBERS: Readonly<Record<string, readonly string[]>> = { Bun: ["file", "write", "spawn", "spawnSync"], process: ["env"] };
const GLOBAL_OBJECTS = new Set(["globalThis", "global", "self", "window"]);

/**
 * Every use of `Bun` or `process` that reaches I/O, or that cannot be seen
 * through (aliasing, destructuring, a computed key), directly or through a
 * global object. Judged by name: a local binding called `process` counts too.
 */
function ioGlobals(path: string, text: string): { line: number; what: string }[] {
  const file = ts.createSourceFile(path, text, ts.ScriptTarget.Latest, true, scriptKind(path));
  const out: { line: number; what: string }[] = [];
  const lineOf = (node: ts.Node): number => file.getLineAndCharacterOfPosition(node.getStart(file)).line + 1;
  /** The member read off `node` by its parent: a name, undefined when computed, null when none is. */
  const memberName = (node: ts.Node): string | undefined | null => {
    const parent = node.parent;
    if (ts.isPropertyAccessExpression(parent) && parent.expression === node) return parent.name.text;
    if (ts.isElementAccessExpression(parent) && parent.expression === node) {
      const key = parent.argumentExpression;
      return ts.isStringLiteral(key) || ts.isNoSubstitutionTemplateLiteral(key) ? key.text : undefined;
    }
    return null;
  };
  const isNamePosition = (node: ts.Identifier): boolean => {
    const parent = node.parent;
    if (ts.isPropertyAccessExpression(parent) || ts.isQualifiedName(parent)) return ts.isPropertyAccessExpression(parent) ? parent.name === node : parent.right === node;
    if (ts.isBindingElement(parent)) return parent.propertyName === node;
    return (ts.isPropertyAssignment(parent) || ts.isPropertyDeclaration(parent) || ts.isMethodDeclaration(parent) ||
      ts.isPropertySignature(parent) || ts.isMethodSignature(parent) || ts.isGetAccessorDeclaration(parent) ||
      ts.isSetAccessorDeclaration(parent) || ts.isEnumMember(parent)) && parent.name === node;
  };
  const judge = (global: string, node: ts.Node): void => {
    const member = memberName(node);
    if (member === null || member === undefined) out.push({ line: lineOf(node), what: `uses ${global} in a way that cannot be checked` });
    else if (IO_MEMBERS[global]!.includes(member)) out.push({ line: lineOf(node), what: `reads ${global}.${member}` });
  };
  const visit = (node: ts.Node): void => {
    if (ts.isIdentifier(node) && !isNamePosition(node)) {
      if (Object.hasOwn(IO_MEMBERS, node.text)) judge(node.text, node);
      else if (GLOBAL_OBJECTS.has(node.text)) {
        const member = memberName(node);
        if (member === null || member === undefined) out.push({ line: lineOf(node), what: `uses ${node.text} in a way that cannot be checked` });
        else if (Object.hasOwn(IO_MEMBERS, member)) judge(member, node.parent);
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(file);
  return out;
}

async function workspaces(): Promise<Map<string, Workspace>> {
  const out = new Map<string, Workspace>();
  for await (const manifest of new Glob("{contexts,apps}/*/package.json").scan({ cwd: ROOT })) {
    const [root, name] = manifest.split("/") as [string, string];
    const pkg = (await Bun.file(`${ROOT}/${manifest}`).json()) as { name?: unknown };
    if (typeof pkg.name === "string") out.set(pkg.name, { kind: root === "contexts" ? "context" : "app", name, dir: `${root}/${name}` });
  }
  return out;
}

async function sourceFiles(): Promise<string[]> {
  const files: string[] = [];
  for await (const path of new Glob("{contexts,apps}/*/src/**/*.{ts,tsx,mts,cts,js,jsx,mjs,cjs}").scan({ cwd: ROOT, dot: true })) {
    if (!path.split("/").includes("node_modules")) files.push(path);
  }
  return files.sort();
}

/** The same files found a second, independent way, so a scan that silently
 *  skips a kind of file fails instead of passing on less. */
function filesOnDisk(): string[] {
  const out: string[] = [];
  const list = (dir: string, recursive: boolean): string[] => {
    try {
      return (readdirSync(dir, { recursive }) as string[]).map((e) => e.split("\\").join("/"));
    } catch {
      return [];
    }
  };
  for (const top of ["contexts", "apps"]) {
    for (const name of list(`${ROOT}/${top}`, false)) {
      for (const entry of list(`${ROOT}/${top}/${name}/src`, true)) {
        const path = `${top}/${name}/src/${entry}`;
        if (CODE.test(path) && !path.split("/").includes("node_modules") && statSync(`${ROOT}/${path}`).isFile()) out.push(path);
      }
    }
  }
  return out.sort();
}

async function sourceRoots(): Promise<string[]> {
  const roots: string[] = [];
  for await (const path of new Glob("{contexts,apps}/*/src/**").scan({ cwd: ROOT, onlyFiles: false, dot: true })) {
    const root = path.split("/").slice(0, 3).join("/");
    if (!roots.includes(root)) roots.push(root);
  }
  return roots;
}

const LAYER_ALLOWS: Readonly<Record<string, readonly string[]>> = {
  domain: ["domain"],
  application: ["domain", "application"],
  "adapters-in": ["domain", "application", "adapters-in"],
  "adapters-out": ["domain", "application", "adapters-out"],
};

function checkContextUse(file: string, from: Extract<Location, { kind: "context" }>, use: Use, index: Map<string, Workspace>): Violation[] {
  const spec = use.spec!;
  const at = `${file}:${use.line} imports "${spec}"`;
  const v = (rule: Rule, why: string): Violation[] => [{ rule, text: `${at} — ${why}` }];
  const test = isTestSide(file);
  if (spec.startsWith(".")) {
    const target = joinPath(file.split("/").slice(0, -1).join("/"), spec);
    const to = target === undefined ? undefined : locate(target);
    if (to === undefined) return v("layers", "it reaches outside every source root");
    if (to.dir !== from.dir) return v("contexts", `it reaches into ${to.dir} by a relative path; contexts never import each other or an app`);
    if (to.kind !== "context" || to.layer === "none") return v("layers", "its target sits in no layer");
    if (!LAYER_ALLOWS[from.layer]!.includes(to.layer)) {
      return v("layers", `${from.layer} may not depend on ${to.layer}; dependencies point inwards: domain <- application <- adapters`);
    }
    if (from.tech !== undefined && to.tech !== undefined && (from.tech !== to.tech || from.layer !== to.layer)) {
      return v("layers", `adapters never import other adapters (${from.layer}/${from.tech} -> ${to.layer}/${to.tech})`);
    }
    return [];
  }
  if (spec.startsWith("/")) return v("layers", "absolute paths are not allowed");
  const pkg = packageOf(spec);
  const workspace = pkg === undefined ? undefined : index.get(pkg.name);
  if (workspace !== undefined) {
    if (workspace.kind === "app") return v("contexts", "contexts never import an app");
    if (workspace.dir !== from.dir) {
      if (from.layer === "adapters-out" && pkg!.subpath === "application") return [];
      return v("contexts", "contexts never import each other; only an out adapter may call another context's application");
    }
    if (!isExportPath(pkg!.subpath)) return v("layers", "import a package only through its export paths (domain, application, adapters/<tech>)");
    const toLayer = pkg!.subpath === "domain" ? "domain" : pkg!.subpath === "application" ? "application" : "adapters";
    const inwards = `${from.layer} may not depend on ${toLayer}; dependencies point inwards: domain <- application <- adapters`;
    if (from.layer === "domain") {
      return v("layers", toLayer === "domain" ? "domain files import each other by relative path, never through the package" : inwards);
    }
    if (from.layer === "application" && toLayer !== "domain") {
      return v("layers", toLayer === "application" ? "application files import their own feature's files by relative path" : inwards);
    }
    if (toLayer === "adapters") return v("layers", "adapters never import other adapters");
    return [];
  }
  if ((from.layer === "domain" || from.layer === "application") && !test && spec !== "zod" && !spec.startsWith("zod/")) {
    return v("layers", `${from.layer} code may use no library but zod: it holds no I/O and no framework`);
  }
  return [];
}

function checkAppUse(file: string, from: Extract<Location, { kind: "app" }>, use: Use, index: Map<string, Workspace>): Violation[] {
  const spec = use.spec!;
  const at = `${file}:${use.line} imports "${spec}"`;
  const out: Violation[] = [];
  let server = false;
  if (spec.startsWith(".")) {
    const target = joinPath(file.split("/").slice(0, -1).join("/"), spec);
    const to = target === undefined ? undefined : locate(target);
    if (to === undefined || to.dir !== from.dir) {
      out.push({ rule: "apps", text: `${at} — an app reaches only its own src/ by relative path; other workspaces through their packages` });
    } else if (from.browser && to.inner[0] !== from.inner[0]) {
      server = true;
    }
  } else if (spec.startsWith("/")) {
    out.push({ rule: "apps", text: `${at} — absolute paths are not allowed` });
  } else {
    const pkg = packageOf(spec);
    const workspace = pkg === undefined ? undefined : index.get(pkg.name);
    if (workspace?.kind === "app") out.push({ rule: "apps", text: `${at} — apps never import other apps` });
    if (workspace?.kind === "context") {
      server = true;
      if (!isExportPath(pkg!.subpath)) {
        out.push({ rule: "apps", text: `${at} — import a context only through its export paths (domain, application, adapters/<tech>)` });
      }
    }
  }
  if (from.browser && server && !use.typeOnly) {
    out.push({
      rule: "browser",
      text: use.inlineTypes
        ? `${at} — 'import { type … }' still loads the module in the browser; write 'import type { … }'`
        : `${at} — browser code imports server code as types only ('import type')`,
    });
  }
  return out;
}

async function check(): Promise<{ files: string[]; onDisk: string[]; roots: string[]; violations: Violation[] }> {
  const index = await workspaces();
  const files = await sourceFiles();
  const violations: Violation[] = [];
  for (const file of files) {
    const from = locate(file)!;
    if (from.kind === "context" && from.layer === "none") {
      violations.push({ rule: "placement", text: `${file} — every context file sits in domain/, application/ or adapters/in|out/<tech>/` });
      continue;
    }
    const text = await Bun.file(`${ROOT}/${file}`).text();
    const core = from.kind === "context" && (from.layer === "domain" || from.layer === "application") && !isTestSide(file);
    if (core) {
      for (const { line, what } of ioGlobals(file, text)) {
        violations.push({ rule: "io", text: `${file}:${line} ${what} — ${from.layer} code does no I/O; take it through an out port or the command` });
      }
    }
    for (const use of usesOf(file, text)) {
      if (use.spec === undefined) {
        violations.push({ rule: "layers", text: `${file}:${use.line} — an import with a computed specifier cannot be checked` });
        continue;
      }
      if (core && !use.typeOnly && use.form !== "member" && isIoModule(use.spec)) {
        violations.push({ rule: "io", text: `${file}:${use.line} imports "${use.spec}" — ${from.layer} code does no I/O; declare an out port` });
      }
      const member = use.form === "member";
      if (from.kind === "context" && from.layer === "adapters-in") {
        const handler = use.names.find((n) => /Handler$/.test(n)) ??
          (!member && /\.handler(\.[cm]?[jt]s)?$/.test(use.spec) ? use.spec : undefined);
        if (handler !== undefined) {
          violations.push({
            rule: "in-adapters",
            text: `${file}:${use.line} uses "${handler}" — in adapters depend on in-port interfaces, never on handler classes`,
          });
        } else if (WHOLE_MODULE.includes(use.form) && wiringTarget(file, use.spec, index) === "application") {
          violations.push({
            rule: "in-adapters",
            text: `${file}:${use.line} takes "${use.spec}" whole (${use.form}) — in adapters import application code by name only, so no handler class can slip through`,
          });
        }
      }
      if (use.form === "loader" && !use.typeOnly && !isCompositionRoot(file) && !isTestSide(file) &&
        wiringTarget(file, use.spec, index) !== undefined) {
        violations.push({
          rule: "wiring",
          text: `${file}:${use.line} loads "${use.spec}" at runtime — only a composition root chooses application and adapter code`,
        });
      }
      if (member) continue;
      violations.push(...(from.kind === "context" ? checkContextUse(file, from, use, index) : checkAppUse(file, from, use, index)));
    }
  }
  return { files, onDisk: filesOnDisk(), roots: await sourceRoots(), violations };
}

const result = await check();
const of = (rule: Rule): string[] => result.violations.filter((v) => v.rule === rule).map((v) => v.text);

describe("architecture", () => {
  test("the scan reads every source file, dot-files and JavaScript included", () => {
    expect(result.roots.length === 0 || result.files.length > 0).toBe(true);
    expect(result.files).toEqual(result.onDisk);
  });

  test("every context file sits in a layer", () => {
    expect(of("placement")).toEqual([]);
  });

  test("dependencies point inwards: domain <- application <- adapters", () => {
    expect(of("layers")).toEqual([]);
  });

  test("contexts never import each other or an app", () => {
    expect(of("contexts")).toEqual([]);
  });

  test("apps import contexts only through their export paths, and never each other", () => {
    expect(of("apps")).toEqual([]);
  });

  test("browser code imports server code as types only", () => {
    expect(of("browser")).toEqual([]);
  });

  test("in adapters depend on in ports, never on handler classes", () => {
    expect(of("in-adapters")).toEqual([]);
  });

  test("domain and application code does no I/O", () => {
    expect(of("io")).toEqual([]);
  });

  test("only composition roots load application and adapter code at runtime", () => {
    expect(of("wiring")).toEqual([]);
  });

  test("workspace directories are kebab-case", () => {
    const bad = result.roots.map((r) => r.split("/")[1]!).filter((n) => !KEBAB.test(n));
    expect(bad).toEqual([]);
  });
});
